<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Lab 5: Hypothesis Testing</title>

<script src="site_libs/header-attrs-2.30/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cerulean.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #204a87; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #8f5902; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #204a87; font-weight: bold; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #ce5c00; font-weight: bold; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>







<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">PUBH 207B: Spring 2026</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="install.html">Getting Started</a>
</li>
<li>
  <a href="about.html">Assignment Guidelines</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Lab Guides
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Lab_1.html">Lab 1</a>
    </li>
    <li>
      <a href="Lab_2.html">Lab 2</a>
    </li>
    <li>
      <a href="Lab_3.html">Lab 3</a>
    </li>
    <li>
      <a href="Lab_4.html">Lab 4</a>
    </li>
    <li>
      <a href="Lab_5.html">Lab 5</a>
    </li>
    <li>
      <a href="Lab_6.html">Lab 6</a>
    </li>
    <li>
      <a href="Lab_7.html">Lab 7</a>
    </li>
    <li>
      <a href="Lab_8.html">Lab 8</a>
    </li>
  </ul>
</li>
<li>
  <a href="help.html">Getting Help</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Lab 5: Hypothesis Testing</h1>

</div>


<p><br></p>
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>In Lab 4 last week, we explored estimation — the first major area of
statistical inference — including how to calculate confidence intervals
for population parameters often of interest in public health, such as
the population mean, difference between two means, population
proportion, and difference between two proportions. Confidence intervals
provide a range of plausible values for a parameter, which allows us
quantify uncertainty in our estimates.</p>
<p>In Lab 5, we will build upon estimation techniques for statistical
inference with <strong>hypothesis testing</strong>, a formal method for
making decisions about population parameters based on sample data. While
confidence intervals allow us to estimate parameters within a margin of
error, hypothesis testing helps us determine whether a population
parameter differs significantly from a hypothesized value.</p>
<p>In Lab 5, you will learn how to conduct both one-sided and two-sided
hypothesis tests for various population parameters, including:</p>
<ul>
<li>A single population mean</li>
<li>The difference between two population means</li>
<li>A single population proportion</li>
<li>The difference between two population proportions</li>
</ul>
<p>You will also see how hypothesis tests and confidence intervals are
closely linked — where confidence intervals can provide insight into the
conclusions we might draw from hypothesis tests. Lab 5 is intentionally
designed to closely follow the structure of Lab 4 so that you can see
the direct relationship between these techniques for statistical
inference.</p>
<p><br></p>
</div>
<div id="objectives" class="section level1">
<h1>Objectives</h1>
<p>After completing Lab 5, you will be able to:</p>
<ol style="list-style-type: decimal">
<li>Formulate null and alternative hypotheses for different types of
tests</li>
<li>Conduct hypothesis tests using R functions</li>
<li>Interpret p-values and make conclusions in context</li>
<li>Relate confidence intervals to hypothesis testing outcomes</li>
</ol>
<p><br></p>
</div>
<div id="tasks" class="section level1">
<h1>Tasks</h1>
<p>In Lab 5, we will continue working with the Framingham Heart Study
teaching dataset. A key assumption we will make is that the baseline
sample is <em>representative</em> of the adult population of the city of
Framingham, MA.</p>
<p>When you are ready to start Lab 5:</p>
<ol style="list-style-type: decimal">
<li>First create a new R Markdown file using the instructions on the
Assignment Guidelines page. Save this <code>.Rmd</code> file in a folder
dedicated to Lab 5 materials.</li>
<li>Next, save the <strong>modified dataset</strong> you created in Lab
2 — called “frmgham2_p1_impute.csv” — in the same folder as your Lab 5 R
Markdown file. This is the same file we used last week in Lab 4.</li>
<li>Finally, proceed to read through and carry out each of the tasks
detailed below. As usual, you will begin by loading R packages, setting
your working directory, and importing the dataset.</li>
</ol>
<p><br></p>
<div id="install-and-load-r-packages" class="section level2">
<h2>1. Install and load R packages</h2>
<p>For Lab 5, you should not need to install any new packages. As usual,
however, we need to start by loading necessary packages with the
<code>library()</code> function, as follows:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="co"># load packages</span></span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a><span class="fu">library</span>(stats)</span></code></pre></div>
<p><br></p>
</div>
<div id="set-your-working-directory" class="section level2">
<h2>2. Set your working directory</h2>
<p>Set your working directory using the <code>setwd()</code> function
(see Assignment Guidelines for detailed instructions).</p>
<pre><code>setwd(&quot;YOUR FILE PATH HERE&quot;)</code></pre>
<p><br></p>
</div>
<div id="import-the-dataset-into-rstudio" class="section level2">
<h2>3. Import the dataset into RStudio</h2>
<p>Use the <code>read.csv()</code> function to bring in the modified
dataset you created in Lab 2. For this to work, the
“frmgham2_p1_impute.csv” file will need to be saved in the working
directory you specified in the above step. Again, this is the same data
file you started with in Lab 4.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" tabindex="-1"></a><span class="co"># import dataset</span></span>
<span id="cb3-2"><a href="#cb3-2" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;frmgham2_p1_impute.csv&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>X)</span></code></pre></div>
<p><br></p>
</div>
<div id="identify-and-modify-variable-types" class="section level2">
<h2>4. Identify and modify variable types</h2>
<p>Before we jump into hypothesis testing, we need to ensure that the
variables we plan to use are in the correct format so they are treated
appropriately in our analyses. This is an important step that you have
practiced several times in previous Labs, and while it may feel
repetitive, it is necessary for avoiding errors and ensuring accurate
interpretation of our results.</p>
<p>As you know very well by now, variables that represent quantifiable
characteristics (e.g., BMI) should be treated as numerical, while
variables that represent categories should be treated as such (i.e., as
categorical or factor variables). So, let’s start by checking variables
types in our dataset:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" tabindex="-1"></a><span class="co"># check variable types</span></span>
<span id="cb4-2"><a href="#cb4-2" tabindex="-1"></a><span class="fu">sapply</span>(data, class)</span></code></pre></div>
<pre><code>##    RANDID       SEX       AGE       BMI   TOTCHOL      EDUC     OBESE 
## &quot;integer&quot; &quot;integer&quot; &quot;integer&quot; &quot;numeric&quot; &quot;integer&quot; &quot;integer&quot; &quot;integer&quot;</code></pre>
<p>Just as we did in Labs 2 and 4, we’ll need to modify the variable
types for sex assigned at birth, attained education, and obesity status.
While these variables take on numerical values in our dataset, these
values do not represent actual quantities — rather, they represent
categories with no inherent quantity. Remember that we also need to
specify whether a categorical or factor variable is ordered or unordered
(i.e., ordinal or nominal). Notice in the code chunks below that, for
<em>unordered</em> (i.e., nominal) categorical variables like sex
assigned at birth and obesity status, we specify
<code>ordered = FALSE</code>, whereas, for <em>ordered</em> (i.e.,
ordinal) categorical variables like attained education, we specify
<code>ordered = TRUE</code>.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" tabindex="-1"></a><span class="co"># convert sex to unordered factor variable</span></span>
<span id="cb6-2"><a href="#cb6-2" tabindex="-1"></a>data<span class="sc">$</span>SEX <span class="ot">&lt;-</span> <span class="fu">factor</span>(data<span class="sc">$</span>SEX, </span>
<span id="cb6-3"><a href="#cb6-3" tabindex="-1"></a>                       <span class="at">levels=</span><span class="fu">c</span>(<span class="st">&quot;1&quot;</span>, <span class="st">&quot;2&quot;</span>), </span>
<span id="cb6-4"><a href="#cb6-4" tabindex="-1"></a>                       <span class="at">ordered=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" tabindex="-1"></a><span class="co"># convert attained education to ordered factor variable</span></span>
<span id="cb7-2"><a href="#cb7-2" tabindex="-1"></a>data<span class="sc">$</span>EDUC <span class="ot">&lt;-</span> <span class="fu">factor</span>(data<span class="sc">$</span>EDUC, </span>
<span id="cb7-3"><a href="#cb7-3" tabindex="-1"></a>                        <span class="at">levels=</span><span class="fu">c</span>(<span class="st">&quot;1&quot;</span>, <span class="st">&quot;2&quot;</span>, <span class="st">&quot;3&quot;</span>, <span class="st">&quot;4&quot;</span>), </span>
<span id="cb7-4"><a href="#cb7-4" tabindex="-1"></a>                        <span class="at">ordered =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" tabindex="-1"></a><span class="co"># convert obesity status to unordered factor variable</span></span>
<span id="cb8-2"><a href="#cb8-2" tabindex="-1"></a>data<span class="sc">$</span>OBESE <span class="ot">&lt;-</span> <span class="fu">factor</span>(data<span class="sc">$</span>OBESE, </span>
<span id="cb8-3"><a href="#cb8-3" tabindex="-1"></a>                         <span class="at">levels=</span><span class="fu">c</span>(<span class="st">&quot;0&quot;</span>, <span class="st">&quot;1&quot;</span>), </span>
<span id="cb8-4"><a href="#cb8-4" tabindex="-1"></a>                         <span class="at">ordered=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<p><br></p>
</div>
<div id="hypothesis-test-for-a-population-mean" class="section level2">
<h2>5. Hypothesis test for a population mean</h2>
<p>As in Lab 4, suppose you are interested in studying body mass index
(BMI) and obesity and want to start by estimating mean BMI of the adult
population of the city of Framingham. In this case, the <em>population
parameter</em> of interest is the population mean of BMI. First, let’s
quickly summarize our dataset using the <code>summary()</code> function
and also visualize the distribution of BMI with a histogram.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" tabindex="-1"></a><span class="co"># summarize dataset</span></span>
<span id="cb9-2"><a href="#cb9-2" tabindex="-1"></a><span class="fu">summary</span>(data)</span></code></pre></div>
<pre><code>##      RANDID        SEX           AGE             BMI           TOTCHOL     
##  Min.   :   2448   1:1944   Min.   :32.00   Min.   :15.54   Min.   :107.0  
##  1st Qu.:2440336   2:2490   1st Qu.:42.00   1st Qu.:23.09   1st Qu.:206.0  
##  Median :4972848            Median :49.00   Median :25.46   Median :234.0  
##  Mean   :4987278            Mean   :49.93   Mean   :25.85   Mean   :236.9  
##  3rd Qu.:7463577            3rd Qu.:57.00   3rd Qu.:28.06   3rd Qu.:263.0  
##  Max.   :9999312            Max.   :70.00   Max.   :56.80   Max.   :696.0  
##  EDUC     OBESE   
##  1:1935   0:3860  
##  2:1281   1: 574  
##  3: 716           
##  4: 502           
##                   
## </code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" tabindex="-1"></a><span class="co"># create a histogram of BMI in the sample</span></span>
<span id="cb11-2"><a href="#cb11-2" tabindex="-1"></a><span class="fu">hist</span>(data<span class="sc">$</span>BMI, <span class="at">breaks =</span> <span class="dv">30</span>)</span></code></pre></div>
<p><img src="Lab_5_files/figure-html/unnamed-chunk-9-1.png" alt="" width="672" /></p>
<p>From the summary of our dataset, we can see the mean BMI in the
sample is 25.85. This aligns with our view of the histogram for BMI,
which shows the bulk of the distribution centered around this value.
Suppose you want to know whether the population of Framingham has an
average BMI that is <em>different</em> from the national average (at the
time of data collection), 25. Using our sample data, we can conduct a
hypothesis test for the value of the population mean to determine — with
a specified level of significance — whether the population mean of BMI
in Framingham is different from the national average.</p>
<p>In statistical hypothesis testing, we start with two competing
hypotheses: the <strong>null hypothesis</strong> (𝐻<sub>0</sub>) and the
<strong>alternative hypothesis</strong> (𝐻<sub>𝑎</sub>). These
hypotheses represent different claims about a population parameter, and
our goal is to use sample data to determine which is more likely to be
true. The null hypothesis is the <em>default assumption</em> that there
is no effect or difference. It represents a baseline or “status quo”
scenario and assumes there is no relationship, difference, or effect.
The alternative hypothesis, on the other hand, is the hypothesis you’re
testing to see if there is evidence of an effect, relationship, or
difference. It states the opposite of the null hypothesis and often
reflects what you suspect or want to confirm using sample data.</p>
<p>For our scenario, the null and alternative hypotheses are as
follows:</p>
<center>
<p><strong>𝐻<sub>0</sub>:</strong> μ = 25<br />
<strong>𝐻<sub>𝑎</sub>:</strong> μ <span
class="math inline">\(\neq\)</span> 25</p>
</center>
<p>Or, in words:</p>
<center>
<p><strong>𝐻<sub>0</sub>:</strong> The mean BMI in Framingham is equal
to the national average, 25.<br />
<strong>𝐻<sub>𝑎</sub>:</strong> The mean BMI in Framingham is different
from the national average, 25.</p>
</center>
<p>The phrasing of our alternative hypothesis —“different from” — is key
because it does not specify a direction (higher or lower), only that the
mean may not be 25. This makes it a <strong>two-sided</strong> test,
because we are considering both possibilities:</p>
<ul>
<li>The population mean BMI in Framingham could be greater than 25.</li>
<li>The population mean BMI in Framingham could be less than 25.</li>
</ul>
<p>Recall from lecture that, after specifying the null and alternative
hypotheses, our next step is to identify the appropriate
<strong>reference distribution</strong> — i.e., the probability
distribution that describes how our test statistic behaves <em>under the
assumption that the null hypothesis is true.</em> When conducting a
hypothesis test for the value of a single population mean, we will use
either the <em>Z</em> or <em>t</em>-distribution. Just like when we
constructed confidence intervals in Lab 4, the appropriate reference
distribution depends on the following conditions:</p>
<ol style="list-style-type: decimal">
<li>Whether the population is normally distributed;</li>
<li>Whether the sample is small or large (≥30); and</li>
<li>Whether the population variance is <em>known</em> or
<em>unknown</em>.</li>
</ol>
<p>We can again use the flowchart below to identify the most appropriate
reference distribution (<em>Z</em> or <em>t</em>) when estimating a
population mean:</p>
<p><br></p>
<p><img src="flowchart_mean2.png" alt="" width="100%" /></p>
<p><br></p>
<p>As in Lab 4, we will assume BMI in the population is approximately
normally distributed with an unknown variance. Following the flowchart
above, under these conditions we can estimate the population mean using
<em>either</em> the standard normal distribution (<em>Z</em>)
<strong>or</strong> the <em>t</em>-distribution. Most often in practice,
the <em>t</em>-distribution will be used (but the results will be very
similar, as the <em>t</em>-distribution approximates the standard normal
distribution with large samples). Let’s take a look at how we can carry
out this task in R using the <code>t.test()</code> function:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" tabindex="-1"></a><span class="co"># one sample t-test for population mean</span></span>
<span id="cb12-2"><a href="#cb12-2" tabindex="-1"></a><span class="fu">t.test</span>(data<span class="sc">$</span>BMI, </span>
<span id="cb12-3"><a href="#cb12-3" tabindex="-1"></a>       <span class="at">mu =</span> <span class="dv">25</span>, </span>
<span id="cb12-4"><a href="#cb12-4" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>, </span>
<span id="cb12-5"><a href="#cb12-5" tabindex="-1"></a>       <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  data$BMI
## t = 13.766, df = 4433, p-value &lt; 2.2e-16
## alternative hypothesis: true mean is not equal to 25
## 95 percent confidence interval:
##  25.72565 25.96667
## sample estimates:
## mean of x 
##  25.84616</code></pre>
<p>First, notice that the code we are using here for this hypothesis
test is very similar to the code we used in Lab 4 to generate a
confidence interval to estimate the population mean BMI. In both cases,
we use the <code>t.test()</code> function and specify the variable of
interest using <code>data$BMI</code>. However, we’ve added a couple of
new arguments, as follows:</p>
<ul>
<li><code>mu = 25</code>: The hypothesized population mean BMI (based on
the null hypothesis).</li>
<li><code>alternative = "two.sided"</code>: Indicates that we are
conducting a two-sided test, since the alternative hypothesis does not
specify a direction.</li>
<li><code>conf.level = 0.95</code>: Just as we did when constructing
confidence intervals, we must specify a desired <strong>confidence
level</strong> for our hypothesis test. The confidence level is
important in hypothesis testing because it determines the <em>threshold
for statistical significance</em> — in other words, how much uncertainty
we are willing to accept when making a decision about the null
hypothesis. Here, we have specified a desired confidence level of 0.95,
or 95%, which means there is a 5% chance of making a Type I error. This
probability is called “alpha” (α) and is referred to as the
<strong>significance level</strong> of a test. In this case, since we
are specifying a confidence level of 95%, this means we have a
significance level, α, of 0.05.</li>
</ul>
<p>Let’s break down the most important parts of the output from our
hypothesis test:</p>
<ul>
<li><strong>Alternative hypothesis</strong>: Specifies the hypothesis
being tested, in this case, that the true (population) mean is not equal
to 25.</li>
<li><strong>Test statistic (<em>t</em>):</strong> Tells us how many
standard errors the sample mean is away from the hypothesized mean (25).
A large <em>t</em>-value (in this case, 13.766) suggests that the sample
mean is significantly different from 25.</li>
<li><strong>p-value</strong>: The p-value represents the probability of
obtaining a test statistic as extreme as (or more extreme than) the one
observed, <em>assuming that the null hypothesis (𝐻<sub>0</sub>) is
true.</em> In other words, the p-value tells us how likely our sample
results would be if there were actually no effect or difference in the
population (i.e., if 𝐻<sub>0</sub> were correct). In this case, the
p-value is very, very small (essentially 0), indicating an extremely low
probability that we would observe a sample mean this far from 25 <em>if
the null hypothesis were true.</em></li>
</ul>
<p>We will use the p-value to make a decision about our null hypothesis.
In general, when the p-value is very small, this means we have enough
evidence to reject the null hypothesis in favor of the alternative
hypothesis. But how small is small? To make a decision about our null
hypothesis (reject or fail to reject) we will compare the p-value to α,
our specified level of significance. Again, this is something we, as the
researcher, will choose in advance of conducting the hypothesis test.
Common choices for α are:</p>
<ul>
<li>0.05 (5%) → Most common in public health and social sciences.</li>
<li>0.01 (1%) → Used when stronger evidence is needed (e.g., medical
studies).</li>
<li>0.10 (10%) → Sometimes used for exploratory research.</li>
</ul>
<p>The general rules for drawing conclusions about a hypothesis test are
as follows:</p>
<ul>
<li>If 𝑝≤𝛼→ Reject 𝐻<sub>0</sub>.
<ul>
<li>The data provide strong evidence against 𝐻<sub>0</sub> , suggesting
that 𝐻<sub>𝑎</sub> is likely true.<br />
</li>
<li>Example: If 𝑝=0.02 and 𝛼=0.05, we reject 𝐻<sub>0</sub>.<br />
</li>
</ul></li>
<li>If 𝑝&gt;𝛼→ Fail to reject 𝐻<sub>0</sub>.
<ul>
<li>The data do not provide enough evidence to reject 𝐻<sub>0</sub>.
This does not mean that 𝐻<sub>0</sub> is true — just that we lack strong
enough evidence to reject it.<br />
</li>
<li>Example: If 𝑝=0.12 and 𝛼=0.05, we fail to reject 𝐻<sub>0</sub>.</li>
</ul></li>
</ul>
<p>Going back to our results above, we have a p-value of &lt; 2.2e-16
(remember, this is scientific notation for an extremely small value,
close to 0). Recall that we set 𝛼=0.05 (again, this should be specified
by the researcher/analyst in advance of conducting the test). Since 𝑝≤𝛼,
we can reject the null hypothesis. We can state our conclusion as
follows:</p>
<blockquote>
<p><em>At a significance level of 0.05, we reject the null hypothesis
(𝐻<sub>0</sub>) and conclude that there is strong statistical evidence
that the true mean BMI in Framingham is different from the national
average of 25.</em></p>
</blockquote>
<p><br></p>
<p>Now, suppose we want to test whether the mean BMI in Framingham is
<em>greater than</em> the national average of 25, rather than just
different from it. This requires a <strong>one-sided</strong> hypothesis
test, where we specifically test if the population mean BMI in
Framingham is significantly higher than 25. In this next example, we
will walk through how to set up and conduct a one-sided <em>t</em>-test
for this scenario.</p>
<p>First, we can state our null and alternative hypotheses as
follows:</p>
<center>
<p><strong>𝐻<sub>0</sub>:</strong> μ ≤ 25<br />
<strong>𝐻<sub>𝑎</sub>:</strong> μ &gt; 25</p>
</center>
<p>Or, in words:</p>
<center>
<p><strong>𝐻<sub>0</sub>:</strong> The mean BMI in Framingham is less
than or equal to the national average, 25.<br />
<strong>𝐻<sub>𝑎</sub>:</strong> The mean BMI in Framingham is greater
than the national average, 25.</p>
</center>
<p>Remember, the null hypothesis (𝐻<sub>0</sub>) always represents the
status quo or no effect/difference. In this case, the status quo is that
the mean BMI in Framingham is not greater than 25 — meaning it could be
equal to or less than 25. The alternative hypothesis (𝐻<sub>𝑎</sub>)
represents the claim we want to test. Since we are specifically
interested in whether the mean BMI is greater than 25, we use a greater
than (&gt;) sign in 𝐻<sub>𝑎</sub>.</p>
<p>The code we will use to carry out this hypothesis test is almost
exactly the same as before — the only difference is that we will specify
<code>alternative = "greater"</code> rather than
<code>alternative = "two.sided"</code> as we did for our two-sided test
above (if testing whether the mean is <em>less</em> than the
hypothesized value, set <code>alternative = "less"</code>):</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" tabindex="-1"></a><span class="co"># one sample t-test for population mean</span></span>
<span id="cb14-2"><a href="#cb14-2" tabindex="-1"></a><span class="fu">t.test</span>(data<span class="sc">$</span>BMI, </span>
<span id="cb14-3"><a href="#cb14-3" tabindex="-1"></a>       <span class="at">mu =</span> <span class="dv">25</span>, </span>
<span id="cb14-4"><a href="#cb14-4" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="st">&quot;greater&quot;</span>, </span>
<span id="cb14-5"><a href="#cb14-5" tabindex="-1"></a>       <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  data$BMI
## t = 13.766, df = 4433, p-value &lt; 2.2e-16
## alternative hypothesis: true mean is greater than 25
## 95 percent confidence interval:
##  25.74503      Inf
## sample estimates:
## mean of x 
##  25.84616</code></pre>
<p>A few things to note about our output:</p>
<ul>
<li>We now see, expectedly, that the alternative hypothesis is that the
“true mean is greater than 25.”</li>
<li>Just as in our previous example, we have a test statistic (t) and
p-value — and, from the tiny p-value, you probably suspect (correctly)
that we will again reject the null hypothesis.</li>
<li>Finally, we see that, where we had a two-sided confidence interval
before, we now have what is sometimes referred to as a “one-sided”
confidence interval, where either the lower or upper bound is set to
negative infinity or positive infinity, respectively. In this case,
since our alternative hypothesis is that the true mean is greater than
25, the upper bound of the one-sided confidence interval is set to
positive infinity (Inf). With a lower bound of 25.74503, we can report,
with 95% confidence, that the true mean is <em>at least</em> this
value.</li>
</ul>
<p>For this one-sided test, we can state our conclusion as follows:</p>
<blockquote>
<p><em>At a significance level of 0.05, we reject the null hypothesis
(𝐻<sub>0</sub>) and conclude that there is strong statistical evidence
that the true mean BMI in Framingham is greater than the national
average of 25.</em></p>
</blockquote>
<p><br></p>
</div>
<div
id="hypothesis-test-for-the-difference-between-two-population-means"
class="section level2">
<h2>6. Hypothesis test for the difference between two population
means</h2>
<p>Again building from Lab 4, suppose we next want to know whether mean
BMI differs by sex assigned at birth — in other words, we want to know
whether there is a statistically significant difference in population
mean BMI between those assigned male and female sex at birth.</p>
<p>First, let’s visualize the distribution of BMI by sex in our
sample:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" tabindex="-1"></a><span class="co"># create side-by-side histograms to show the distribution of BMI by sex at birth</span></span>
<span id="cb16-2"><a href="#cb16-2" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="#cb16-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> BMI, <span class="at">fill =</span> SEX)) <span class="sc">+</span></span>
<span id="cb16-4"><a href="#cb16-4" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(<span class="at">color=</span><span class="st">&quot;#e9ecef&quot;</span>, <span class="at">alpha=</span><span class="fl">0.5</span>, <span class="at">position =</span> <span class="st">&#39;identity&#39;</span>) <span class="sc">+</span></span>
<span id="cb16-5"><a href="#cb16-5" tabindex="-1"></a>    <span class="fu">scale_fill_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&#39;Males&#39;</span>, <span class="st">&#39;Females&#39;</span>)) <span class="sc">+</span></span>
<span id="cb16-6"><a href="#cb16-6" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="Lab_5_files/figure-html/unnamed-chunk-13-1.png" alt="" width="672" /></p>
<p><em>See Lab 4 for a detailed breakdown of the code chunk used to
generate this side-by-side histogram.</em></p>
<p>From the histogram we can see that the distributions of BMI among
males and females overlap substantially. However, the center of the
distribution appears to be slightly higher (further to the right) among
males than females. We can use a hypothesis test to determine whether or
not there is a statistically significant difference between the two
population means.</p>
<p>Let’s start by stating the null and alternative hypotheses:</p>
<center>
<p><strong>𝐻<sub>0</sub>:</strong> μ<sub>male</sub> = μ<sub>female</sub>
or equivalently, μ<sub>male</sub> − μ<sub>female</sub> = 0<br />
<strong>𝐻<sub>𝑎</sub>:</strong> μ<sub>male</sub> <span
class="math inline">\(\neq\)</span> μ<sub>female</sub> or equivalently,
μ<sub>male</sub> − μ<sub>female</sub> <span
class="math inline">\(\neq\)</span> 0</p>
</center>
<p>Or, in words:</p>
<center>
<p><strong>𝐻<sub>0</sub>:</strong> There is no difference in mean BMI
between males and females in the population.<br />
<strong>𝐻<sub>𝑎</sub>:</strong> The true mean BMI differs between males
and females in the population.</p>
</center>
<p>This is a two-sided test because we are testing for any difference,
rather than specifically whether BMI is higher in one group compared to
the other.</p>
<p>Next, recall from lecture that the appropriate reference distribution
(for a difference in means) depends on four conditions:</p>
<ol style="list-style-type: decimal">
<li>Whether or not the populations are normally distributed;</li>
<li>Whether or not the sample sizes are large;</li>
<li>Whether or not the population variances are known; and finally,</li>
<li>Whether or not the population variances are equal.</li>
</ol>
<p>As in Lab 4, we can use the flowchart below to identify the most
appropriate reference distribution (<em>Z</em>, <em>t</em>, or
<em>t’</em>) when estimating the difference in population means:</p>
<p><img src="flowchart_diff_means.png" alt="" width="100%" /></p>
<p><br></p>
<p>To estimate the difference in mean BMI between males and females in
Framingham, let’s first make the following assumptions:</p>
<ol style="list-style-type: decimal">
<li>BMI is normally distributed in both populations.</li>
<li>We have large samples.</li>
<li>Population variances are unknown.</li>
</ol>
<p>The fourth condition — whether the population variances are equal or
not — requires further investigation. In Lab 4, you learned three
possible approaches: the <strong>F-test</strong> for equality of
variances (appropriate for normally distributed or approximately
normally distributed data); <strong>Levene’s test</strong> (appropriate
for slightly skewed data); or, an alternative to Levene’s test, the
<strong>Fligner-Killeen’s test</strong> (which is actually the most
robust to departures from normality).</p>
<p>Since we have already gone through the steps of determining equality
of variances in Lab 4, we won’t repeat those steps here. Just be sure to
return to Lab 4 for guidance on this step when working on future
assignments.</p>
<p>We know from our work in Lab 4 that the variances of BMI among males
and females are <em>not</em> equal. Following our flowchart above, we
can see that either the <em>Z</em> or <em>t’</em> reference distribution
would be appropriate in this case.</p>
<p>We will opt to carry out a two-sample <em>t-test</em> with unequal
variances (i.e., Welch’s t-test) using the <code>t.test()</code>
function as follows:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" tabindex="-1"></a><span class="co"># two-sample t-test for difference in mean BMI by sex at birth</span></span>
<span id="cb18-2"><a href="#cb18-2" tabindex="-1"></a><span class="fu">t.test</span>(BMI <span class="sc">~</span> SEX, </span>
<span id="cb18-3"><a href="#cb18-3" tabindex="-1"></a>       <span class="at">data =</span> data, </span>
<span id="cb18-4"><a href="#cb18-4" tabindex="-1"></a>       <span class="at">var.equal =</span> <span class="cn">FALSE</span>, </span>
<span id="cb18-5"><a href="#cb18-5" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>, </span>
<span id="cb18-6"><a href="#cb18-6" tabindex="-1"></a>       <span class="at">mu =</span> <span class="dv">0</span>, </span>
<span id="cb18-7"><a href="#cb18-7" tabindex="-1"></a>       <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  BMI by SEX
## t = 4.812, df = 4424.5, p-value = 1.544e-06
## alternative hypothesis: true difference in means between group 1 and group 2 is not equal to 0
## 95 percent confidence interval:
##  0.3404038 0.8084815
## sample estimates:
## mean in group 1 mean in group 2 
##        26.16875        25.59431</code></pre>
<p><br></p>
<p>As in our previous example, the code we are using should feel
familiar from Lab 4. Here, however, we have specified a couple of
additional arguments:</p>
<ul>
<li><code>alternative = "two.sided"</code>: Specifies a two-tailed test
to check for any difference (not just greater or less).</li>
<li><code>mu = 0</code>: Tests whether the difference in means is equal
to 0 (i.e., no difference between groups).</li>
<li><code>conf.level = 0.95</code>: Specifies a confidence level of 0.95
or 95%, meaning 𝛼=0.05.</li>
</ul>
<p>From the output, we can see we have a p-value of 1.544e-06 (remember,
this is scientific notation for a very small value, in this case,
0.000001544). Since 𝑝≤𝛼, we can reject the null hypothesis. We can state
our conclusion as follows:</p>
<blockquote>
<p><em>At a significance level of 0.05, we reject the null hypothesis
and conclude that there is strong statistical evidence that the mean BMI
differs between males and females in the population.</em></p>
</blockquote>
<p><br></p>
<p>Now, suppose we want to test whether the mean BMI among males is
greater than the mean BMI among females, rather than just different. As
we saw in our one-sample <em>t</em>-test previously, specifying a
direction in this way (“greater than” rather than “different from”)
requires a one-sided hypothesis test, where we specifically test if the
population mean BMI for males is significantly higher than that for
females. In the next example, we will walk through how to set up and
conduct a one-sided t-test to evaluate this claim.</p>
<p>First, we can state our null and alternative hypotheses as
follows:</p>
<center>
<p><strong>𝐻<sub>0</sub>:</strong> μ<sub>male</sub> ≤ μ<sub>female</sub>
or equivalently, μ<sub>male</sub> − μ<sub>female</sub> ≤ 0<br />
<strong>𝐻<sub>𝑎</sub>:</strong> μ<sub>male</sub> &gt; μ<sub>female</sub>
or equivalently, μ<sub>male</sub> − μ<sub>female</sub> &gt; 0</p>
</center>
<p>Or, in words:</p>
<center>
<p><strong>𝐻<sub>0</sub>:</strong> The mean BMI among males is less than
or equal to the mean BMI among females.<br />
<strong>𝐻<sub>𝑎</sub>:</strong> The mean BMI among males is greater than
the mean BMI among females.</p>
</center>
<p>From the previous example, we already know that both the <em>Z</em>
and <em>t’</em> reference distributions are appropriate to carry out
this test. We will again opt to carry out a two-sample <em>t-test</em>
with unequal variances (i.e., Welch’s t-test) using the
<code>t.test()</code> function. Note that the only change we need to
make to our code is changing the alternative hypothesis from “two.sided”
to “greater” as follows:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" tabindex="-1"></a><span class="co"># two-sample t-test for difference in mean BMI by sex</span></span>
<span id="cb20-2"><a href="#cb20-2" tabindex="-1"></a><span class="fu">t.test</span>(BMI <span class="sc">~</span> SEX, </span>
<span id="cb20-3"><a href="#cb20-3" tabindex="-1"></a>       <span class="at">data =</span> data, </span>
<span id="cb20-4"><a href="#cb20-4" tabindex="-1"></a>       <span class="at">var.equal =</span> <span class="cn">FALSE</span>, </span>
<span id="cb20-5"><a href="#cb20-5" tabindex="-1"></a>       <span class="at">alternative =</span> <span class="st">&quot;greater&quot;</span>, </span>
<span id="cb20-6"><a href="#cb20-6" tabindex="-1"></a>       <span class="at">mu =</span> <span class="dv">0</span>, </span>
<span id="cb20-7"><a href="#cb20-7" tabindex="-1"></a>       <span class="at">conf.level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  BMI by SEX
## t = 4.812, df = 4424.5, p-value = 7.72e-07
## alternative hypothesis: true difference in means between group 1 and group 2 is greater than 0
## 95 percent confidence interval:
##  0.3780437       Inf
## sample estimates:
## mean in group 1 mean in group 2 
##        26.16875        25.59431</code></pre>
<p><br></p>
<p>Once again, since the p-value (p-value = 7.72e-07) is smaller than
our significance level (𝛼=0.05), we will reject the null hypothesis. We
can state our conclusion as follows:</p>
<blockquote>
<p><em>At a significance level of 0.05, we reject the null hypothesis
and conclude that the mean BMI among males is greater than the mean BMI
among females in the population.</em></p>
</blockquote>
<p><br></p>
</div>
<div id="hypothesis-test-for-a-population-proportion"
class="section level2">
<h2>7. Hypothesis test for a population proportion</h2>
<p>In Lab 4, we estimated the proportion of the adult population in
Framingham with obesity (defined as BMI&gt;30). Now, we will take this a
step further by conducting a one-sample hypothesis test for a population
proportion to determine whether the prevalence of obesity in Framingham
at baseline differs significantly from the national obesity prevalence
at the time of data collection, which was about 13% (recall that the
Framingham Heart Study started in 1948 − national obesity prevalence has
tripled since then). This test will allow us to assess whether the
observed obesity prevalence in Framingham is statistically different
from the national prevalence or if any difference could be due to random
variation in our sample.</p>
<p>As usual, let’s start by defining the null and alternative hypotheses
for this test:</p>
<center>
<p><strong>𝐻<sub>0</sub>:</strong> p = 0.13<br />
<strong>𝐻<sub>𝑎</sub>:</strong> p <span
class="math inline">\(\neq\)</span> 0.13</p>
</center>
<p>Or, in words:</p>
<center>
<p><strong>𝐻<sub>0</sub>:</strong> Obesity prevalence in Framingham is
equal to the national obesity prevalence of 13%.<br />
<strong>𝐻<sub>𝑎</sub>:</strong> Obesity prevalence in Framingham is
different from the national obesity prevalence of 13%.</p>
</center>
<p>To carry out this hypothesis test, we will use the
<code>prop.test()</code> function. The notation for this test is
<code>prop.test(x, n, p = p0)</code>, where <code>x</code> will be the
number of individuals classified as obese in the sample, <code>n</code>
is the total sample size, and <code>p0</code> is the hypothesized value
(in this case, the national prevalence of 0.13). As we have done in the
previous examples, we will also need to specify an alternative
hypothesis. Let’s first obtain the number of obese individuals
(<code>x</code>) so that we have the information we need to carry out
the test:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" tabindex="-1"></a><span class="co"># generate a table to count number of obese individuals in the sample</span></span>
<span id="cb22-2"><a href="#cb22-2" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>OBESE)</span></code></pre></div>
<pre><code>## 
##    0    1 
## 3860  574</code></pre>
<p>From the output, we can see there are 574 individuals classified as
obese, out of a total sample of 4,434. We can now enter all of the
values into the <code>prop.test()</code> function to carry out this
test, as follows:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" tabindex="-1"></a><span class="co"># one-sample proportion test</span></span>
<span id="cb24-2"><a href="#cb24-2" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="dv">574</span>, <span class="dv">4434</span>, </span>
<span id="cb24-3"><a href="#cb24-3" tabindex="-1"></a>          <span class="at">p =</span> <span class="fl">0.13</span>, </span>
<span id="cb24-4"><a href="#cb24-4" tabindex="-1"></a>          <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>, </span>
<span id="cb24-5"><a href="#cb24-5" tabindex="-1"></a>          <span class="at">conf.level =</span> <span class="fl">0.95</span>, </span>
<span id="cb24-6"><a href="#cb24-6" tabindex="-1"></a>          <span class="at">correct =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  1-sample proportions test without continuity correction
## 
## data:  574 out of 4434, null probability 0.13
## X-squared = 0.011678, df = 1, p-value = 0.9139
## alternative hypothesis: true p is not equal to 0.13
## 95 percent confidence interval:
##  0.119893 0.139657
## sample estimates:
##         p 
## 0.1294542</code></pre>
<p>From out output, we see the p-value is very large (0.9139), meaning
the probability of obtaining an obesity prevalence as extreme as 12.95%
(the prevalence in the sample) if the true population proportion were
13% is very high. Since 𝑝&gt;0.05 (or any common significance level), we
<em>fail to reject</em> the null hypothesis. This means we do not have
enough statistical evidence to conclude that the obesity prevalence in
Framingham is different from the national prevalence of 13%.</p>
<p>Note that the 95% confidence interval for the true population
proportion ranges from 11.99% to 13.97%. Since 13% falls within this
interval, it is a plausible value for the true obesity prevalence,
reinforcing our decision to <strong>not</strong> reject the null
hypothesis.</p>
<p><br></p>
</div>
<div
id="hypothesis-test-for-the-difference-between-two-population-proportions"
class="section level2">
<h2>8. Hypothesis test for the difference between two population
proportions</h2>
<p>Finally, suppose we want to test whether there is a statistically
significant difference in obesity prevalence between those assigned male
and female sex at birth in Framingham. We can state the null and
alternative hypotheses as follows:</p>
<center>
<p><strong>𝐻<sub>0</sub>:</strong> p<sub>male</sub> = p<sub>female</sub>
or equivalently, p<sub>male</sub> − p<sub>female</sub> = 0<br />
<strong>𝐻<sub>𝑎</sub>:</strong> p<sub>male</sub> <span
class="math inline">\(\neq\)</span> p<sub>female</sub> or equivalently,
p<sub>male</sub> − p<sub>female</sub> <span
class="math inline">\(\neq\)</span> 0</p>
</center>
<p>Or, in words:</p>
<center>
<p><strong>𝐻<sub>0</sub>:</strong> The prevalence of obesity is the same
for males and females in the population.<br />
<strong>𝐻<sub>𝑎</sub>:</strong> The prevalence of obesity is different
between males and females.</p>
</center>
<p>As when we generated a confidence interval for the difference in
proportions in Lab 4, we first need to know the number of obese
individuals by sex assigned at birth in the sample. We also need the
total number of males and females in the sample. We can obtain these
values using the ‘table’ command as follows:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" tabindex="-1"></a><span class="co"># generate counts of obesity and totals by sex assigned at birth</span></span>
<span id="cb26-2"><a href="#cb26-2" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>SEX, data<span class="sc">$</span>OBESE) <span class="co"># counts of obesity by sex at birth</span></span></code></pre></div>
<pre><code>##    
##        0    1
##   1 1712  232
##   2 2148  342</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>SEX) <span class="co"># total by sex at birth</span></span></code></pre></div>
<pre><code>## 
##    1    2 
## 1944 2490</code></pre>
<p>The code chunks above generate two tables in the Console window. The
first provides a count of obese individuals by sex assigned at birth,
and the second provides the totals by sex. From the first table, we see
there are 232 males with obesity, and there are 342 females with obesity
in the sample. From the second table, we see there are a total of 1,944
males in the sample and 2,490 females. Next, we will use these values to
test whether there is a statistically significant difference in
population proportions using the <code>prop.test()</code> function as
follows:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" tabindex="-1"></a><span class="co"># two-sample hypothesis test for difference in obesity prevalence by sex assigned at birth</span></span>
<span id="cb30-2"><a href="#cb30-2" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="fu">c</span>(<span class="dv">232</span>, <span class="dv">342</span>), <span class="fu">c</span>(<span class="dv">1944</span>, <span class="dv">2490</span>), </span>
<span id="cb30-3"><a href="#cb30-3" tabindex="-1"></a>          <span class="at">alternative =</span> <span class="st">&quot;two.sided&quot;</span>, </span>
<span id="cb30-4"><a href="#cb30-4" tabindex="-1"></a>          <span class="at">conf.level =</span> <span class="fl">0.95</span>, </span>
<span id="cb30-5"><a href="#cb30-5" tabindex="-1"></a>          <span class="at">correct =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  2-sample test for equality of proportions without continuity correction
## 
## data:  c(232, 342) out of c(1944, 2490)
## X-squared = 3.1413, df = 1, p-value = 0.07633
## alternative hypothesis: two.sided
## 95 percent confidence interval:
##  -0.037768267  0.001752599
## sample estimates:
##    prop 1    prop 2 
## 0.1193416 0.1373494</code></pre>
<p>Once again, this two-sample test examines whether obesity prevalence
differs between males and females in the Framingham population. As the
p-value (0.07633) is greater than 0.05, we <em>fail to reject the null
hypothesis</em> — meaning we cannot conclude there is a statistically
significant difference in obesity prevalence between males (11.93%) and
females (13.73%) in the population.</p>
<p>This result aligns with our findings from Lab 4, where we constructed
a confidence interval for the difference in population proportions. As
we can see again in the output here, the 95% confidence interval
(-0.0378, 0.0018) includes zero, which reinforces our conclusion that
the true difference in obesity prevalence between males and females
could be zero (i.e., no difference). The results of our hypothesis test
confirm our previous conclusion that any observed difference is likely
due to random variation (i.e., chance).</p>
<p><br></p>
</div>
</div>
<div id="summary" class="section level1">
<h1>Summary</h1>
<p>In Lab 5, we applied hypothesis testing to assess differences in
population means and proportions using data from the Framingham Heart
Study. We conducted:</p>
<ul>
<li>A one-sample t-test to evaluate whether the mean BMI in Framingham
differs from a national standard.</li>
<li>A two-sample t-test to compare BMI between males and females.</li>
<li>A one-sample proportion test to determine whether obesity prevalence
in Framingham differs from the national prevalence.</li>
<li>A two-sample proportion test to test for differences in obesity
prevalence by sex assigned at birth in Framingham.</li>
</ul>
<p>These methods are fundamental tools in public health research, as
they allow us to:</p>
<ol style="list-style-type: decimal">
<li>Evaluate health disparities (e.g., differences in obesity burden
across populations).</li>
<li>Assess intervention effectiveness (e.g., does a new program reduce
smoking prevalence in a population?).</li>
<li>Inform public health policy (e.g., is a community’s disease or risk
factor prevalence significantly higher than national benchmarks?).</li>
</ol>
<p>So far, we have focused on comparing one or two groups at a time.
However, in public health research, we often need to compare multiple
groups — for example, assessing differences across racial/ethnic groups
or evaluating disease prevalence across different income or educational
levels. Next week, we will learn about ANOVA (Analysis of Variance),
which extends hypothesis testing to compare means across three or more
groups. Understanding hypothesis testing principles from Lab 5 will help
us interpret ANOVA results, as the underlying logic remains the
same.</p>
<p>When you are ready, please submit the following to the Lab 5
assignment page on Canvas:</p>
<ol style="list-style-type: decimal">
<li>An R Markdown document, which has a <code>.Rmd</code> extension</li>
<li>A knitted <code>.html</code> file</li>
</ol>
<p>Please reach out to me at <a href="mailto:jenny.wagner@csus.edu"
class="email">jenny.wagner@csus.edu</a> if you have any questions. See
you in class!</p>
<p><br></p>
<hr />
<p><strong>Jenny Wagner, PhD, MPH</strong><br />
Assistant Professor<br> Department of Public Health<br> California State
University, Sacramento<br> <a href="mailto:jenny.wagner@csus.edu"
class="email">jenny.wagner@csus.edu</a></p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
