<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Lab 3: Probability Distributions</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cerulean.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #204a87; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #8f5902; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #204a87; font-weight: bold; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #ce5c00; font-weight: bold; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>







<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">PUBH 207B: Spring 2025</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="course_schedule.html">Course Schedule</a>
</li>
<li>
  <a href="install.html">Getting Started</a>
</li>
<li>
  <a href="about.html">Assignment Guidelines</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Lab Guides
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Lab_1.html">Lab 1</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Lab 3: Probability Distributions</h1>

</div>


<p><br> <strong>Jenny Wagner, PhD, MPH</strong> <br> Department of
Public Health <br> California State University, Sacramento <br> <br></p>
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>Probability distributions are a fundamental concept in statistics and
public health research. They describe how the values of a random
variable are distributed, giving us a mathematical framework to quantify
uncertainty and make predictions about data. In simpler terms, a
probability distribution shows the likelihood of different outcomes for
a given variable. In the real world, they are used to describe patterns
in health-related data, such as the distribution of disease incidence,
patient wait times, or the effectiveness of interventions.</p>
<p>There are two main types of probability distributions:</p>
<ol style="list-style-type: decimal">
<li><strong>Discrete Probability Distributions:</strong> These are used
for variables that can take on a <em>finite or countable</em> number of
distinct values. Each value has a specific probability associated with
it. For example, the number of new cases of a disease reported in a week
is a discrete variable, as it represents a count (e.g., 0, 1, 2, …). We
will focus on two commonly used discrete probability distributions:</li>
</ol>
<ul>
<li><strong>Binomial Distribution:</strong> Models the probability of a
specific number of successes in a fixed number of independent trials,
where each trial has the same probability of success. For example, we
might use the binomial distribution to estimate the probability of a
certain number of patients recovering after a new treatment or to
predict the proportion of smokers in a sample of adults.</li>
<li><strong>Poisson Distribution:</strong> Models the probability of a
given number of events occurring in a fixed interval of time or space,
assuming the events happen independently and at a constant average rate.
For example, we might use the Poisson distribution to model the number
of emergency room visits in a day or estimate the number of disease
outbreaks in a year in a specific region.</li>
</ul>
<ol start="2" style="list-style-type: decimal">
<li><strong>Continuous Probability Distributions:</strong> These are
used for variables that can take on an <em>infinite number of
values</em> within a given range. Probabilities are represented as areas
under a curve, as the probability of any single exact value is
effectively zero. For example, body mass index (BMI) is a continuous
variable, as it can take on any value within a range (e.g., 18.5, 24.7).
The most commonly used continuous probability distribution is the normal
distribution, which is widely used to model data in public health.</li>
</ol>
<ul>
<li><strong>Normal Distribution:</strong> A continuous probability
distribution characterized by a symmetric, bell-shaped curve. It is
defined by its mean, which determines the center of the distribution,
and standard deviation, which determines its spread. The normal
distribution is often used to analyze continuous health metrics (e.g.,
BMI, cholesterol levels, blood pressure, etc.) and serves as the
foundation for many statistical methods, including hypothesis testing
and confidence interval estimation, due to its mathematical properties
and role in the Central Limit Theorem.</li>
</ul>
<p>A solid understanding of probability distributions will be important
a we move toward statistical methods like estimation and hypothesis
testing in the coming weeks.</p>
<p><br></p>
</div>
<div id="objectives" class="section level1">
<h1>Objectives</h1>
<p>After completing Lab 3, you will be able to:</p>
<ol style="list-style-type: decimal">
<li>Construct and interpret a discrete probability distribution.</li>
<li>Calculate probabilities using discrete and continuous probability
distributions for public health scenarios.</li>
<li>Calculate measures of center and spread for discrete probability
distributions.</li>
<li>Visualize discrete and continuous probability distributions.</li>
</ol>
<p><br></p>
</div>
<div id="part-1-discrete-probability-distributions-based-on-real-data"
class="section level1">
<h1>Part 1: Discrete Probability Distributions Based on Real Data</h1>
<p>For the first part of this Lab, we will use the following scenario:
Suppose patients who were involved in a problem gambling treatment
program were surveyed about co-occurring drug and alcohol addictions.
Let the discrete random variable ‘X’ represent the number of
co-occurring addictive substances used by the subjects. The dataset
labeled “substances.csv” contains two variables: (1) a study ID number
corresponding to each individual patient; and (2) the number of
substances used by the corresponding patient.</p>
<p>When you are ready to start Lab 3:</p>
<ol style="list-style-type: decimal">
<li>First create a new R Markdown file using the instructions on the
Assignment Guidelines page. Save this <code>.Rmd</code> file in a folder
dedicated to Lab 3 materials.</li>
<li>Next, download and save the dataset called “substances.csv” in the
same folder as your Lab 3 R Markdown file.</li>
<li>Finally, proceed to read through and carry out each of the tasks
detailed below. As usual, you will begin by loading R packages, setting
your working directory, and importing the dataset.</li>
</ol>
<p><br></p>
<div id="install-and-load-r-packages" class="section level2">
<h2>1. Install and load R packages</h2>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="co"># load packages</span></span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="#cb1-4" tabindex="-1"></a><span class="fu">library</span>(stats)</span></code></pre></div>
<p><br></p>
</div>
<div id="set-your-working-directory" class="section level2">
<h2>2. Set your working directory</h2>
<p>Set your working directory using the <code>setwd()</code> function -
but remember to paste your own file path between the parentheses (see
Assignment Guidelines for detailed instructions).</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" tabindex="-1"></a><span class="co"># set working directory</span></span>
<span id="cb2-2"><a href="#cb2-2" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;/Volumes/GoogleDrive/My Drive/1_CSUS/2024-2025/Spring 2025/PUBH 207B/Website/PUBH-207B-S25&quot;</span>)</span></code></pre></div>
<p><br></p>
</div>
<div id="import-the-dataset-into-rstudio" class="section level2">
<h2>3. Import the dataset into RStudio</h2>
<p>Use the <code>read.csv()</code> function to import the
“substances.csv” data file. Remember that this file must be saved in the
working directory you specified in the above step.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" tabindex="-1"></a><span class="co"># import dataset</span></span>
<span id="cb3-2"><a href="#cb3-2" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;substances.csv&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>X)</span></code></pre></div>
<p><br></p>
</div>
</div>
<div id="construct-a-discrete-probability-distribution"
class="section level1">
<h1>4. Construct a discrete probability distribution</h1>
<p>To construct a discrete probability distribution for the number of
co-occurring substance addictions, we first need to create a table
showing the frequency and relative frequency for this discrete
distribution as follows:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" tabindex="-1"></a><span class="co"># construct frequency table and save it as a new dataframe</span></span>
<span id="cb4-2"><a href="#cb4-2" tabindex="-1"></a>subs <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">table</span>(data<span class="sc">$</span>substances))</span></code></pre></div>
<p>A brief breakdown of this code:</p>
<ul>
<li><code>table(data$substances)</code>: Creates a frequency table of
the substances variable in the data dataset. The table counts the
occurrences of each unique value in the <code>substances</code>
variable, producing a summary of how often each substance appears.</li>
<li><code>as.data.frame()</code>: Converts the frequency table into a
data frame format. This allows the frequency information to be stored as
a two-column data frame: one column for the unique values in substances
and another column for their respective counts.</li>
<li><code>subs &lt;- ...</code>: Assigns the resulting data frame to the
object <code>subs</code>. The <code>subs</code> object will now contain
a data frame where:
<ul>
<li>The first column (generically called <code>Var1</code>) holds the
unique values of the substances variable.</li>
<li>The second column (<code>Freq</code>) holds the corresponding
frequencies (counts) of those values.</li>
</ul></li>
</ul>
<p>Let’s click on the <code>subs</code> object in our Environment to see
what it looks like. We can also use the <code>print()</code> command as
follows:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" tabindex="-1"></a><span class="co"># print frequency table</span></span>
<span id="cb5-2"><a href="#cb5-2" tabindex="-1"></a><span class="fu">print</span>(subs)</span></code></pre></div>
<pre><code>##    Var1 Freq
## 1     0  144
## 2     1  342
## 3     2  142
## 4     3   72
## 5     4   39
## 6     5   20
## 7     6    6
## 8     7    9
## 9     8    2
## 10    9    1</code></pre>
<p>As expected, we see two variables, <code>Var1</code> (the number of
co-occurring substances) and <code>Freq</code> (the number of people in
our dataset with each correponding number of co-occurring
substances).</p>
<p>When constructing a discrete probability distribution, the goal is to
represent the likelihood of each category or value in the dataset. To do
this, we need to calculate <strong>relative frequencies</strong>, which
represent the proportion of occurrences for each category relative to
the total number of observations. For our scenario here, this means
calculating the relative frequency of each number of co-occurring
substances by dividing the frequency in each category by the total
number of observations. We can create a new variable for the relative
frequencies in our <code>subs</code> object as follows:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" tabindex="-1"></a><span class="co"># create a new variable for the relative frequency </span></span>
<span id="cb7-2"><a href="#cb7-2" tabindex="-1"></a>    <span class="co"># relative frequency = the proportion of subjects with each number of substances used</span></span>
<span id="cb7-3"><a href="#cb7-3" tabindex="-1"></a>subs <span class="ot">&lt;-</span> subs <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">rel_freq =</span> Freq<span class="sc">/</span>(<span class="fu">sum</span>(Freq)))</span>
<span id="cb7-4"><a href="#cb7-4" tabindex="-1"></a><span class="fu">print</span>(subs)</span></code></pre></div>
<pre><code>##    Var1 Freq    rel_freq
## 1     0  144 0.185328185
## 2     1  342 0.440154440
## 3     2  142 0.182754183
## 4     3   72 0.092664093
## 5     4   39 0.050193050
## 6     5   20 0.025740026
## 7     6    6 0.007722008
## 8     7    9 0.011583012
## 9     8    2 0.002574003
## 10    9    1 0.001287001</code></pre>
<p>This line of code creates a new variable called <code>rel_freq</code>
using the frequencies generated previously. A more detailed
explanation:</p>
<ul>
<li><code>subs</code>: This is the data frame being modified. It
contains a frequency table where one column (Freq) holds the counts for
each category.</li>
<li><code>%&gt;%</code>: This is the pipe operator (we’ve seen this
several times now!). It allows for chaining commands together in a
readable way, passing the result of one operation as input to the
next.</li>
<li><code>mutate()</code>: A function used to create new variables or
modify existing ones in a data frame. In this case, it adds a new column
called <code>rel_freq</code> to the <code>subs</code> data frame.</li>
<li><code>rel_freq = Freq / (sum(Freq))</code>:
<ul>
<li><code>Freq</code>: Refers to the column in subs that holds the raw
frequencies (counts) of each category.</li>
<li><code>sum(Freq)</code>: Calculates the total frequency (i.e., the
sum of all counts in the Freq column).</li>
<li><code>Freq / (sum(Freq))</code>: Divides each frequency value by the
total frequency to compute the relative frequency for each category.
This gives the proportion of the total observations that fall into each
category, a necessary step in constructing a probability
distribution.</li>
</ul></li>
<li><code>subs &lt;-</code>: Reassigns the modified data frame back to
the subs object, updating it with the new rel_freq column.</li>
</ul>
<p>Let’s again use the <code>print()</code> command to view the updated
data frame as follows:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" tabindex="-1"></a><span class="co"># print frequency table</span></span>
<span id="cb9-2"><a href="#cb9-2" tabindex="-1"></a><span class="fu">print</span>(subs)</span></code></pre></div>
<pre><code>##    Var1 Freq    rel_freq
## 1     0  144 0.185328185
## 2     1  342 0.440154440
## 3     2  142 0.182754183
## 4     3   72 0.092664093
## 5     4   39 0.050193050
## 6     5   20 0.025740026
## 7     6    6 0.007722008
## 8     7    9 0.011583012
## 9     8    2 0.002574003
## 10    9    1 0.001287001</code></pre>
<p>As expected, we see a new variable, <code>rel_freq</code>, which
tells us the relative frequency (or proportion) of the sample with each
corresponding number of co-occurring substance addictions.</p>
<p><br></p>
<p>Next, let’s visualize this probability distribution using the
<code>barplot</code> function:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" tabindex="-1"></a><span class="co"># generate a simple bar chart for sex</span></span>
<span id="cb11-2"><a href="#cb11-2" tabindex="-1"></a><span class="fu">barplot</span>(subs<span class="sc">$</span>rel_freq, </span>
<span id="cb11-3"><a href="#cb11-3" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">&quot;Number of co-occurring substance addictions&quot;</span>, </span>
<span id="cb11-4"><a href="#cb11-4" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">&quot;Relative frequency&quot;</span>, </span>
<span id="cb11-5"><a href="#cb11-5" tabindex="-1"></a>        <span class="at">col =</span> <span class="st">&quot;gray&quot;</span>,</span>
<span id="cb11-6"><a href="#cb11-6" tabindex="-1"></a>        <span class="at">names.arg =</span> subs<span class="sc">$</span>Var1)</span></code></pre></div>
<p><img src="Lab_3_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p><br></p>
</div>
<div
id="calculate-probabilities-from-a-discrete-probability-distribution"
class="section level1">
<h1>5. Calculate probabilities from a discrete probability
distribution</h1>
<p>Before we begin to use our discrete probability distribution to
obtain probabilities, it will be helpful to convert the discrete random
variable X (currently labeled ‘Var1’ and defined as a factor variable)
to a numeric variable. We need to use a two-step process to convert a
factor variable to a numeric variable. We first need to convert the
factor variable to a character variable using the
<code>as.character()</code> function, then to a numeric variable using
the <code>as.numeric()</code> function. Very strange, I know. If we do
not first convert to a character variable, R will drop the category
corresponding to zero co-occurring substances, and we don’t want that to
happen.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" tabindex="-1"></a><span class="co"># convert factor to numeric variable</span></span>
<span id="cb12-2"><a href="#cb12-2" tabindex="-1"></a>subs<span class="sc">$</span>Var1 <span class="ot">&lt;-</span> <span class="fu">as.character</span>(subs<span class="sc">$</span>Var1) <span class="co"># first convert to character </span></span>
<span id="cb12-3"><a href="#cb12-3" tabindex="-1"></a>subs<span class="sc">$</span>Var1 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(subs<span class="sc">$</span>Var1)</span></code></pre></div>
<p>Now that we have formatted our variables appropriately, we can
calculate probabilities for specified numbers of co-occurring substance
addictions. For example, suppose we want to know the probability that an
individual selected at random uses five addictive substances. For a
specific number of co-occurring substances (in this case, 5), we can
actually find this answer by looking directly at our discrete
probability distribution. When we look at the row where
<code>Var1</code> is equal to 5, we see that <code>rel_freq</code> is
equal to 0.025740026. This means that the probability a randomly
selected person from the sample has 5 co-occurring substance addictions
is 0.025740026, or about 2.6%. To obtain this answer using code (we’ll
see the utility of this approach shortly), the following will work:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" tabindex="-1"></a><span class="co"># obtain the probability of 5 co-occurring substance addictions</span></span>
<span id="cb13-2"><a href="#cb13-2" tabindex="-1"></a>subs <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Var1 <span class="sc">==</span> <span class="dv">5</span>) <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="fu">sum</span>(rel_freq))</span></code></pre></div>
<pre><code>##   sum(rel_freq)
## 1    0.02574003</code></pre>
<p>This line of code is essentially taking the sum of relative
frequencies where <code>Var1</code> is equal to 5. Let’s look at a few
more examples, but this time for range of values…</p>
<p><strong>What is the probability that an individual selected at random
used <em>fewer than three</em> addictive substances?</strong></p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" tabindex="-1"></a><span class="co"># obtain the probability of fewer than 3 co-occurring substance addictions</span></span>
<span id="cb15-2"><a href="#cb15-2" tabindex="-1"></a>subs <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Var1 <span class="sc">&lt;</span> <span class="dv">3</span>) <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="fu">sum</span>(rel_freq))</span></code></pre></div>
<pre><code>##   sum(rel_freq)
## 1     0.8082368</code></pre>
<p>Here, we are taking the sum of relative frequencies where
<code>Var1</code> is less than 3. We find the probability that a
randomly selected person from the sample uses fewer than 3 addictive
substances is 0.8082368, or about 80.8%.</p>
<p><strong>What is the probability that an individual selected at random
used <em>more than six</em> addictive substances?</strong></p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" tabindex="-1"></a>subs <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Var1 <span class="sc">&gt;</span> <span class="dv">6</span>) <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="fu">sum</span>(rel_freq))</span></code></pre></div>
<pre><code>##   sum(rel_freq)
## 1    0.01544402</code></pre>
<p>Here, we are taking the sum of relative frequencies where
<code>Var1</code> is greater than 6. We find the probability that a
randomly selected person from the sample uses greater than 6 addictive
substances is 0.01544402, or about 1.5%.</p>
<p><strong>What is the probability that an individual selected at random
used <em>between 2 and 5</em> addictive substances?</strong></p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" tabindex="-1"></a>subs <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Var1 <span class="sc">&gt;=</span> <span class="dv">2</span> <span class="sc">&amp;</span> Var1 <span class="sc">&lt;=</span> <span class="dv">5</span>) <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">summarise</span>(<span class="fu">sum</span>(rel_freq))</span></code></pre></div>
<pre><code>##   sum(rel_freq)
## 1     0.3513514</code></pre>
<p>This one is a little trickier. Here, we are taking the sum of
relative frequencies where <code>Var1</code> is both greater than or
equal to 2 <em>and</em> less than or equal to 5 (in other words, where
<code>Var1</code> is between 2 and 5). We find the probability that a
randomly selected person from the sample uses between 2 and 5 addictive
substances is 0.3513514, or about 35.1%.</p>
<div
id="calculate-measures-of-center-and-spread-for-a-discrete-probability-distribution"
class="section level2">
<h2>6. Calculate measures of center and spread for a discrete
probability distribution</h2>
<p>Measures of center and spread are useful for summarizing and
interpreting a discrete probability distribution. The mean, or expected
value, provides the central tendency, indicating the average outcome we
would expect if the process were repeated many times. The variance
measures how spread out the values are around the mean, which provides
insight to the variability or uncertainty in the distribution. The
standard deviation, as the square root of the variance, provides a more
interpretable measure of spread in the same units as the variable.
Together, these measures allow us to describe the distribution’s
behavior, compare different groups, and draw meaningful conclusions in a
public health context.</p>
<p>We can use the following to obtain the mean, variance, and standard
deviation of this discrete probability distribution:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">rep</span>(subs<span class="sc">$</span>Var1, subs<span class="sc">$</span>Freq)) <span class="co"># mean</span></span></code></pre></div>
<pre><code>## [1] 1.572716</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" tabindex="-1"></a><span class="fu">var</span>(<span class="fu">rep</span>(subs<span class="sc">$</span>Var1, subs<span class="sc">$</span>Freq)) <span class="co"># variance</span></span></code></pre></div>
<pre><code>## [1] 2.095543</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" tabindex="-1"></a><span class="fu">sd</span>(<span class="fu">rep</span>(subs<span class="sc">$</span>Var1, subs<span class="sc">$</span>Freq)) <span class="co"># standard deviation</span></span></code></pre></div>
<pre><code>## [1] 1.447599</code></pre>
<p>We find the mean number of co-occurring substance addictions is
approximately 1.57; this represents the average number of addictions we
expect across a population. We find the variance and standard deviation
are 2.095543 and 1.447599, respectively. These measures of spread give
us a sense of how spread out the values are around the mean and are
particularly useful when comparing the spread across different
populations.</p>
<p><br></p>
</div>
<div id="part-2-theoretical-probability-distributions"
class="section level2">
<h2>Part 2: Theoretical Probability Distributions</h2>
<p>So far in this lab, we’ve explored a discrete probability
distribution based on real data, calculating key measures like relative
frequencies, the mean, variance, and standard deviation. This concrete
example helps us understand how probability distributions summarize and
describe patterns in data.</p>
<p>Next, we’ll shift our focus to theoretical probability distributions
— specifically, the binomial, Poisson, and normal distributions. These
distributions are widely used in public health to model and predict
outcomes in scenarios where we don’t have all the data but need to make
informed estimates. By working with these distributions, we can
calculate probabilities for specific events, explore relationships
between variables, and gain deeper insight into uncertainty and
variability in public health contexts. Let’s see how these tools allow
us to answer practical probability questions and ultimately support
evidence-based decision-making.</p>
<p><br></p>
<p>LEAVING OFF HERE</p>
<div id="a.-binomial-distribution" class="section level3">
<h3>a. Binomial distribution</h3>
<p>Scenario: Based on data collected by the Centers for Disease Control
and Prevention (CDC), an estimate of the percentage of adults who have
at some point in their life been told they have hypertension is 48.1%
percent. Assume that ‘N’ is sufficiently large relative to ‘n’ that the
binomial distribution may be used to find the desired probabilities.</p>
<p>Suppose we select a simple random sample of 20 U.S. adults and assume
that the probability that each has been diagnosed with hypertension is
.48.</p>
<div
id="i.-what-is-the-probability-that-exactly-eight-have-been-diagnosed-with-hypertension"
class="section level4">
<h4>i. What is the probability that exactly eight have been diagnosed
with hypertension?</h4>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" tabindex="-1"></a><span class="co"># the function &#39;dbinom&#39; is used to find the probability for a specific number of successes</span></span>
<span id="cb27-2"><a href="#cb27-2" tabindex="-1"></a><span class="co"># the syntax is dbinom(x, n, p) where x = number of successes, n = number of trials, and p = probability of success</span></span>
<span id="cb27-3"><a href="#cb27-3" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" tabindex="-1"></a><span class="fu">dbinom</span>(<span class="dv">8</span>, <span class="dv">20</span>, <span class="fl">0.48</span>)</span></code></pre></div>
<pre><code>## [1] 0.1387513</code></pre>
</div>
</div>
<div
id="ii.-what-is-the-probability-that-fewer-than-eight-have-been-diagnosed-with-hypertension"
class="section level3">
<h3>ii. What is the probability that fewer than eight have been
diagnosed with hypertension?</h3>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" tabindex="-1"></a><span class="co"># the function &#39;pbinom&#39; is used to find the cumulative probability up to a specific number of successes</span></span>
<span id="cb29-2"><a href="#cb29-2" tabindex="-1"></a>    <span class="co"># in other words, &#39;pbinom&#39; gives us P(X &lt;= x)</span></span>
<span id="cb29-3"><a href="#cb29-3" tabindex="-1"></a><span class="co"># the syntax is pbinom(x, n, p) where x = number of successes, n = number of trials, and p = probability of success</span></span>
<span id="cb29-4"><a href="#cb29-4" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" tabindex="-1"></a><span class="fu">pbinom</span>(<span class="dv">7</span>, <span class="dv">20</span>, <span class="fl">0.48</span>)</span></code></pre></div>
<pre><code>## [1] 0.1739206</code></pre>
</div>
<div
id="iii.-what-is-the-probability-that-eight-or-more-have-been-diagnosed-with-hypertension"
class="section level3">
<h3>iii. What is the probability that eight or more have been diagnosed
with hypertension?</h3>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" tabindex="-1"></a><span class="co"># since &#39;pbinom&#39; will give us the probability that 7 or fewer have been diagnosed with hypertension, we must subtract this probability from 1 to get the probability that 8 or more will have hypertension.</span></span>
<span id="cb31-2"><a href="#cb31-2" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pbinom</span>(<span class="dv">7</span>, <span class="dv">20</span>, <span class="fl">0.48</span>)</span></code></pre></div>
<pre><code>## [1] 0.8260794</code></pre>
</div>
<div
id="iv.-what-is-the-probability-that-between-eight-and-12-inclusive-have-been-diagnosed-with-hypertension"
class="section level3">
<h3>iv. What is the probability that between eight and 12 (inclusive)
have been diagnosed with hypertension?</h3>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" tabindex="-1"></a><span class="fu">pbinom</span>(<span class="dv">12</span>, <span class="dv">20</span>, <span class="fl">0.48</span>) <span class="sc">-</span> <span class="fu">pbinom</span>(<span class="dv">7</span>, <span class="dv">20</span>, <span class="fl">0.48</span>)</span></code></pre></div>
<pre><code>## [1] 0.7291661</code></pre>
</div>
</div>
<div
id="b-find-the-mean-and-variance-of-the-number-of-people-diagnosed-with-hypertension-in-samples-of-size-20."
class="section level2">
<h2>(b) Find the mean and variance of the number of people diagnosed
with hypertension in samples of size 20.</h2>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" tabindex="-1"></a><span class="co"># one way to do this is to calculate the mean and variance using R as a simple calculator</span></span>
<span id="cb35-2"><a href="#cb35-2" tabindex="-1"></a><span class="co"># remember that the mean of a binomial distribution is equal to n(p) and variance is n(p)(1-p)</span></span>
<span id="cb35-3"><a href="#cb35-3" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" tabindex="-1"></a><span class="dv">20</span><span class="sc">*</span><span class="fl">0.48</span> <span class="co"># mean</span></span></code></pre></div>
<pre><code>## [1] 9.6</code></pre>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" tabindex="-1"></a><span class="dv">20</span><span class="sc">*</span><span class="fl">0.48</span><span class="sc">*</span>(<span class="dv">1</span><span class="fl">-0.48</span>) <span class="co"># variance</span></span></code></pre></div>
<pre><code>## [1] 4.992</code></pre>
</div>
<div id="c-create-a-plot-to-visualize-this-binomial-distribution."
class="section level2">
<h2>(c) Create a plot to visualize this binomial distribution.</h2>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" tabindex="-1"></a>success <span class="ot">&lt;-</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">20</span></span>
<span id="cb39-2"><a href="#cb39-2" tabindex="-1"></a><span class="fu">plot</span>(success, <span class="fu">dbinom</span>(success, <span class="at">size=</span><span class="dv">20</span>, <span class="at">prob=</span><span class="fl">0.48</span>), <span class="at">type =</span> <span class="st">&#39;h&#39;</span>)</span></code></pre></div>
<p><img src="Lab_3_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
</div>
</div>
<div id="poisson-distribution" class="section level1">
<h1>3. Poisson distribution</h1>
<p>Question text: In a certain population, an average of 13 new cases of
esophageal cancer are diagnosed each year.</p>
<div
id="a-suppose-the-annual-incidence-of-esophageal-cancer-follows-a-poisson-distribution."
class="section level2">
<h2>(a) Suppose the annual incidence of esophageal cancer follows a
Poisson distribution.</h2>
<div
id="i.-what-is-the-probability-that-in-a-given-year-the-number-of-newly-diagnosed-cases-of-esophageal-cancer-will-be-exactly-10"
class="section level3">
<h3>i. What is the probability that, in a given year, the number of
newly diagnosed cases of esophageal cancer will be exactly 10?</h3>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" tabindex="-1"></a><span class="co"># note: the function &#39;dpois&#39; gives the probability that exactly &#39;x&#39; number of events occur within the time period.</span></span>
<span id="cb40-2"><a href="#cb40-2" tabindex="-1"></a><span class="co"># the syntax for &#39;dpois&#39; is ppois(x, lambda), where &#39;x&#39; is the number of events of interest, and lambda is the mean.</span></span>
<span id="cb40-3"><a href="#cb40-3" tabindex="-1"></a></span>
<span id="cb40-4"><a href="#cb40-4" tabindex="-1"></a><span class="fu">dpois</span>(<span class="dv">10</span>, <span class="dv">13</span>)</span></code></pre></div>
<pre><code>## [1] 0.08587015</code></pre>
</div>
<div
id="ii.-what-is-the-probability-that-in-a-given-year-the-number-of-newly-diagnosed-cases-of-esophageal-cancer-will-be-12-or-fewer"
class="section level3">
<h3>ii. What is the probability that, in a given year, the number of
newly diagnosed cases of esophageal cancer will be 12 or fewer?</h3>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" tabindex="-1"></a><span class="co"># note: the function &#39;ppois&#39; gives the cumulative probability that &#39;x&#39; or fewer events occur within the time period.</span></span>
<span id="cb42-2"><a href="#cb42-2" tabindex="-1"></a><span class="co"># the syntax for &#39;ppois&#39; is ppois(x, lambda), where &#39;x&#39; is the number of events of interest, and lambda is the mean.</span></span>
<span id="cb42-3"><a href="#cb42-3" tabindex="-1"></a></span>
<span id="cb42-4"><a href="#cb42-4" tabindex="-1"></a><span class="fu">ppois</span>(<span class="dv">12</span>, <span class="dv">13</span>)</span></code></pre></div>
<pre><code>## [1] 0.4631047</code></pre>
</div>
<div
id="iii.-what-is-the-probability-that-in-a-given-year-the-number-of-newly-diagnosed-cases-of-esophageal-cancer-will-be-at-least-eight"
class="section level3">
<h3>iii. What is the probability that, in a given year, the number of
newly diagnosed cases of esophageal cancer will be at least eight?</h3>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">ppois</span>(<span class="dv">7</span>, <span class="dv">13</span>)</span></code></pre></div>
<pre><code>## [1] 0.9459718</code></pre>
</div>
<div
id="iv.-what-is-the-probability-that-in-a-given-year-the-number-of-newly-diagnosed-cases-of-esophageal-cancer-will-be-between-nine-and-15-inclusive"
class="section level3">
<h3>iv. What is the probability that, in a given year, the number of
newly diagnosed cases of esophageal cancer will be between nine and 15
(inclusive)?</h3>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" tabindex="-1"></a><span class="fu">ppois</span>(<span class="dv">15</span>, <span class="dv">13</span>) <span class="sc">-</span> <span class="fu">ppois</span>(<span class="dv">8</span>, <span class="dv">13</span>)</span></code></pre></div>
<pre><code>## [1] 0.663849</code></pre>
</div>
</div>
<div id="b-create-a-plot-to-visualize-this-poisson-distribution."
class="section level2">
<h2>(b) Create a plot to visualize this Poisson distribution.</h2>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" tabindex="-1"></a>events <span class="ot">&lt;-</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">30</span></span>
<span id="cb48-2"><a href="#cb48-2" tabindex="-1"></a><span class="fu">plot</span>(events, <span class="fu">dpois</span>(events, <span class="at">lambda =</span> <span class="dv">13</span>), <span class="at">type =</span> <span class="st">&#39;h&#39;</span>)</span></code></pre></div>
<p><img src="Lab_3_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
</div>
</div>
<div id="normal-distribution" class="section level1">
<h1>4. Normal distribution</h1>
<p>Question text: One of the variables collected in Birth Registry data
is pounds gained during pregnancy. According to data from the entire
registry for 2021, the number of pounds gained during pregnancy was
approximately normally distributed with a mean of 30.23 pounds and a
standard deviation of 13.84 pounds.</p>
<div
id="a-find-the-probability-that-a-randomly-selected-mother-in-2021-gained"
class="section level2">
<h2>(a) Find the probability that a randomly selected mother in 2021
gained:</h2>
<div id="i.-less-than-15-pounds-during-pregnancy."
class="section level3">
<h3>i. Less than 15 pounds during pregnancy.</h3>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" tabindex="-1"></a><span class="co"># note: the &#39;pnorm&#39; function gives the cumulative probability that a random variable X takes a value less than or equal to x. The syntax for &#39;pnorm&#39; is pnorm(x, mean, sd).</span></span>
<span id="cb49-2"><a href="#cb49-2" tabindex="-1"></a></span>
<span id="cb49-3"><a href="#cb49-3" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">15</span>, <span class="fl">30.23</span>, <span class="fl">13.84</span>)</span></code></pre></div>
<pre><code>## [1] 0.1355716</code></pre>
</div>
<div id="ii.-more-than-40-pounds-during-pregnancy."
class="section level3">
<h3>ii. More than 40 pounds during pregnancy.</h3>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="dv">40</span>, <span class="fl">30.23</span>, <span class="fl">13.84</span>)</span></code></pre></div>
<pre><code>## [1] 0.2401174</code></pre>
</div>
<div id="iii.-between-15-and-40-pounds-during-pregnancy."
class="section level3">
<h3>iii. Between 15 and 40 pounds during pregnancy.</h3>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="dv">40</span>, <span class="fl">30.23</span>, <span class="fl">13.84</span>) <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="dv">15</span>, <span class="fl">30.23</span>, <span class="fl">13.84</span>)</span></code></pre></div>
<pre><code>## [1] 0.6243109</code></pre>
</div>
</div>
<div id="b-create-a-plot-to-visualize-this-normal-distribution."
class="section level2">
<h2>(b) Create a plot to visualize this normal distribution.</h2>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, <span class="fl">30.23</span>, <span class="fl">13.84</span>), <span class="at">from=</span><span class="dv">0</span>, <span class="at">to=</span><span class="dv">60</span>)</span></code></pre></div>
<p><img src="Lab_3_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
