<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Lab 8: Logistic Regression</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cerulean.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #204a87; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #8f5902; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #204a87; font-weight: bold; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #ce5c00; font-weight: bold; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>







<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">PUBH 207B: Spring 2025</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="install.html">Getting Started</a>
</li>
<li>
  <a href="about.html">Assignment Guidelines</a>
</li>
<li>
  <a href="workflow.html">Assignment Workflow</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Lab Guides
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Lab_1.html">Lab 1</a>
    </li>
  </ul>
</li>
<li>
  <a href="help.html">Getting Help</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Lab 8: Logistic Regression</h1>

</div>


<p><br></p>
<p><strong>Jenny Wagner, PhD, MPH</strong> <br> Department of Public
Health <br> California State University, Sacramento <br> <br></p>
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>In Lab 8, we’ll shift our focus from linear regression (our topic
last week) to a new type of model: logistic regression. While linear
regression is useful for predicting continuous outcomes (like systolic
blood pressure, BMI, or area-level disease incidence rates), logistic
regression is used when the <em>outcome is binary</em> — that is, when
there are only two possible values. In public health research, this
often means modeling the presence or absence of a health outcome, such
as disease status or event occurrence.</p>
<p>We’ll use the Framingham Heart Study dataset to investigate how
baseline characteristics like age, sex, smoking status, BMI, blood
pressure, cholesterol, and diabetes relate to the risk of having a heart
attack during the study’s follow-up period. Our outcome of interest here
is binary: whether or not a participant experienced a heart attack
during the follow-up period (yes/no).</p>
<p>Like linear regression, logistic regression allows us to examine
associations between predictors and an outcome, but instead of
estimating the mean of a continuous outcome, it models the probability
of a binary outcome. Because probabilities must fall between 0 and 1,
logistic regression uses the logit function (the log of the odds) to
transform probabilities into a continuous scale that can be modeled
using a linear equation.</p>
<p>There are several important assumptions to keep in mind when using
logistic regression:</p>
<ul>
<li>The outcome variable is binary.</li>
<li>Observations are independent of one another.</li>
<li>There is a linear relationship between the log odds of the outcome
and each predictor.</li>
<li>There is no high multicollinearity among predictors.</li>
<li>The sample size is sufficiently large for stable estimates
<ul>
<li>A general rule of thumb is that there should be at least 10
observations per predictor variable. For example, if you plan to use 7
predictor variables in a logistic regression model, you should have a
sample size of at least 70 observations.</li>
</ul></li>
</ul>
<p><br></p>
</div>
<div id="objectives" class="section level1">
<h1>Objectives</h1>
<p>After completing Lab 8, you will be able to:</p>
<ol style="list-style-type: decimal">
<li>Fit a logistic regression model using R/RStudio.</li>
<li>Check assumptions of logistic regression.</li>
<li>Exponentiate regression coefficients to obtain odds ratios.</li>
<li>Interpret odds ratios.</li>
</ol>
<p><br></p>
</div>
<div id="tasks" class="section level1">
<h1>Tasks</h1>
<p>For Lab 8, we will continue our exploration of risk factors for
cardiovascular disease using the Framingham Heart Study. In this Lab we
will focus on a specific outcome: the occurrence of heart attacks during
the follow-up period (called <code>MI_FCHD</code>). Our goal is to build
a logistic regression model using baseline characteristics collected at
the start of the study to identify significant predictors of heart
attack risk.</p>
<p>When you are ready to start Lab 8:</p>
<ol style="list-style-type: decimal">
<li>First create a new R Markdown file using the instructions on the
Assignment Guidelines page. Save this <code>.Rmd</code> file in a folder
dedicated to Lab 8 materials.</li>
<li>Next, download the file called “frmgham2.csv” from Canvas and save
it in the same folder as your Lab 8 R Markdown file. Note that this is
the original Framingham Heart Study dataset, which we have used in prior
Labs.</li>
<li>Finally, proceed to read through and carry out each of the tasks
detailed below. As usual, you will begin by loading R packages, setting
your working directory, and importing the dataset.</li>
</ol>
<p><br></p>
<div id="install-and-load-r-packages" class="section level2">
<h2>1. Install and load R packages</h2>
<p>We will use the following packages in this Lab:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="co"># load packages</span></span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a><span class="fu">library</span>(naniar)</span>
<span id="cb1-4"><a href="#cb1-4" tabindex="-1"></a><span class="fu">library</span>(stats)</span>
<span id="cb1-5"><a href="#cb1-5" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb1-6"><a href="#cb1-6" tabindex="-1"></a><span class="fu">library</span>(performance) </span></code></pre></div>
<p><br></p>
</div>
<div id="set-your-working-directory" class="section level2">
<h2>2. Set your working directory</h2>
<p>Set your working directory using the <code>setwd()</code> function
(see Assignment Guidelines for detailed instructions).</p>
<pre><code>setwd(&quot;YOUR FILE PATH HERE&quot;)</code></pre>
<p><br></p>
</div>
<div id="import-the-dataset-into-rstudio" class="section level2">
<h2>3. Import the dataset into RStudio</h2>
<p>Use the <code>read.csv()</code> function to import the “frmgham2.csv”
dataset. For this to work, this file will need to be saved in the
working directory you specified in the above step.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" tabindex="-1"></a><span class="co"># import dataset</span></span>
<span id="cb3-2"><a href="#cb3-2" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;frmgham2.csv&quot;</span>)</span></code></pre></div>
<p><br></p>
</div>
<div id="prepare-the-dataset-for-analysis" class="section level2">
<h2>4. Prepare the dataset for analysis</h2>
<p>As we are starting here with the <em>original</em> Framingham Heart
Study dataset (and not the cleaned version we have used in a few prior
Labs), we will need to follow a few steps to prepare the dataset for
analysis. First, we will filter the dataset to contain only the baseline
sample. This is because we are going to investigate the association
between baseline characteristics and heart attack risk.</p>
<blockquote>
<p>Note: Although we will be analyzing only the baseline observations,
our outcome of interest — whether a participant experienced a heart
attack (recorded in the dataset as <code>MI_FCHD</code>) applies to the
entire follow-up period. This variable is binary, where “1” indicates
that a participant experienced a heart attack at some point during
follow-up, and “0” indicates they did not.</p>
</blockquote>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" tabindex="-1"></a><span class="co"># filter to include only baseline time period</span></span>
<span id="cb4-2"><a href="#cb4-2" tabindex="-1"></a>data_sub <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(PERIOD <span class="sc">==</span> <span class="dv">1</span>)</span></code></pre></div>
<p>In analyzing data from prospective cohort studies such as this, the
standard approach is to start with a disease-free population and observe
the occurrence of new cases over time. As such, we will restrict our
analysis to individuals without prevalent heart disease at baseline. We
can filter the dataset to include only participants without heart
disease at baseline (indicated by the variable <code>PREVCHD</code>) as
follows:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" tabindex="-1"></a><span class="co"># filter to include only individuals without prevalent heart disease at baseline</span></span>
<span id="cb5-2"><a href="#cb5-2" tabindex="-1"></a>data_sub <span class="ot">&lt;-</span> data_sub <span class="sc">%&gt;%</span> <span class="fu">filter</span>(PREVCHD <span class="sc">==</span> <span class="dv">0</span>)</span></code></pre></div>
<p>Next, let’s retain only the variables we plan to use in our
regression analysis - including our outcome and predictors of interest -
so that our dataset is smaller and more manageable. As discussed above,
we will investigate sex, age, BMI, systolic blood pressure, total
cholesterol level, smoking status, and diabetes status as possible
predictors of heart attack risk. We can retain these variables using the
<code>select()</code> function as follows:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" tabindex="-1"></a><span class="co"># select variables we want to use in regression analysis</span></span>
<span id="cb6-2"><a href="#cb6-2" tabindex="-1"></a>data_reg <span class="ot">&lt;-</span> data_sub <span class="sc">%&gt;%</span> <span class="fu">select</span>(RANDID, SEX, AGE, BMI, SYSBP, TOTCHOL, CURSMOKE, DIABETES, MI_FCHD)</span></code></pre></div>
<p>Before we begin our analysis, let’s quickly check for missing data by
nesting the <code>is.na()</code> function within the
<code>colSums()</code> function as follows:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" tabindex="-1"></a><span class="co"># count number of missing values for each variable</span></span>
<span id="cb7-2"><a href="#cb7-2" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(data_reg))</span></code></pre></div>
<pre><code>##   RANDID      SEX      AGE      BMI    SYSBP  TOTCHOL CURSMOKE DIABETES 
##        0        0        0       19        0       50        0        0 
##  MI_FCHD 
##        0</code></pre>
<p>From the output, we can see there are 19 missing values for BMI
(<code>BMI</code>) and 50 missing values for total cholesterol
(<code>TOTCHOL</code>). Since there are very few missing values relative
to our sample size, let’s address missingness using complete case
analysis (i.e., remove rows with any missing values), as follows:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" tabindex="-1"></a><span class="co"># keep &quot;complete cases&quot; for regression variables</span></span>
<span id="cb9-2"><a href="#cb9-2" tabindex="-1"></a>data_reg <span class="ot">&lt;-</span> data_reg[<span class="fu">complete.cases</span>(data_reg), ] </span></code></pre></div>
<p>Finally, as we have done in prior Labs, let’s identify variables
types and modify them as needed. In the past, we have used the
<code>class()</code> function to check variable types one at a time. As
a quicker alternative, we can use the <code>str()</code> command to
check the structure of our dataset, including variable types, as
follows:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" tabindex="-1"></a><span class="co"># identify variable type for all variables in the dataset</span></span>
<span id="cb10-2"><a href="#cb10-2" tabindex="-1"></a><span class="fu">str</span>(data_reg)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    4172 obs. of  9 variables:
##  $ RANDID  : int  2448 6238 9428 10552 11252 11263 12629 12806 14367 16365 ...
##  $ SEX     : int  1 2 1 2 2 2 2 2 1 1 ...
##  $ AGE     : int  39 46 48 61 46 43 63 45 52 43 ...
##  $ BMI     : num  27 28.7 25.3 28.6 23.1 ...
##  $ SYSBP   : num  106 121 128 150 130 ...
##  $ TOTCHOL : int  195 250 245 225 285 228 205 313 260 225 ...
##  $ CURSMOKE: int  0 0 1 1 1 0 0 1 0 1 ...
##  $ DIABETES: int  0 0 0 0 0 0 0 0 0 0 ...
##  $ MI_FCHD : int  1 0 0 0 0 1 0 0 0 0 ...</code></pre>
<p>Our output contains a list of the variables in our dataset, followed
by the variable type, where “num” indicates a variable is a continuous
numerical variable and “int” indicates a variable is an integer (i.e., a
discrete numerical variable). For our regression analysis, this
distinction between continuous numerical variables (“num”) and discrete
numerical variables (“int”) will not matter. However, as we have done
many times in the past, we should convert any variables that represent
categories (rather than quantities) to factor variables. In our dataset,
this includes sex, smoking status, diabetes status, and occurrence of
heart attacks during follow-up. We can modify these variables as
follows:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" tabindex="-1"></a><span class="co"># convert sex to unordered factor variable</span></span>
<span id="cb12-2"><a href="#cb12-2" tabindex="-1"></a>data_reg<span class="sc">$</span>SEX <span class="ot">&lt;-</span> <span class="fu">factor</span>(data_reg<span class="sc">$</span>SEX, </span>
<span id="cb12-3"><a href="#cb12-3" tabindex="-1"></a>                         <span class="at">levels=</span><span class="fu">c</span>(<span class="st">&quot;1&quot;</span>, <span class="st">&quot;2&quot;</span>), </span>
<span id="cb12-4"><a href="#cb12-4" tabindex="-1"></a>                         <span class="at">ordered=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" tabindex="-1"></a><span class="co"># convert smoking status to unordered factor variable</span></span>
<span id="cb13-2"><a href="#cb13-2" tabindex="-1"></a>data_reg<span class="sc">$</span>CURSMOKE <span class="ot">&lt;-</span> <span class="fu">factor</span>(data_reg<span class="sc">$</span>CURSMOKE, </span>
<span id="cb13-3"><a href="#cb13-3" tabindex="-1"></a>                         <span class="at">levels=</span><span class="fu">c</span>(<span class="st">&quot;0&quot;</span>, <span class="st">&quot;1&quot;</span>), </span>
<span id="cb13-4"><a href="#cb13-4" tabindex="-1"></a>                         <span class="at">ordered=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" tabindex="-1"></a><span class="co"># convert diabetes status to unordered factor variable</span></span>
<span id="cb14-2"><a href="#cb14-2" tabindex="-1"></a>data_reg<span class="sc">$</span>DIABETES <span class="ot">&lt;-</span> <span class="fu">factor</span>(data_reg<span class="sc">$</span>DIABETES, </span>
<span id="cb14-3"><a href="#cb14-3" tabindex="-1"></a>                         <span class="at">levels=</span><span class="fu">c</span>(<span class="st">&quot;0&quot;</span>, <span class="st">&quot;1&quot;</span>), </span>
<span id="cb14-4"><a href="#cb14-4" tabindex="-1"></a>                         <span class="at">ordered=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" tabindex="-1"></a><span class="co"># convert occurrence of heart attack to unordered factor variable</span></span>
<span id="cb15-2"><a href="#cb15-2" tabindex="-1"></a>data_reg<span class="sc">$</span>MI_FCHD <span class="ot">&lt;-</span> <span class="fu">factor</span>(data_reg<span class="sc">$</span>MI_FCHD, </span>
<span id="cb15-3"><a href="#cb15-3" tabindex="-1"></a>                         <span class="at">levels=</span><span class="fu">c</span>(<span class="st">&quot;0&quot;</span>, <span class="st">&quot;1&quot;</span>), </span>
<span id="cb15-4"><a href="#cb15-4" tabindex="-1"></a>                         <span class="at">ordered=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<p><br></p>
</div>
<div id="exploratory-data-analysis" class="section level2">
<h2>5. Exploratory data analysis</h2>
<p>Before we build our logistic regression model, we should be familiar
with the variables we plan to include. First, we should know the
distribution of our outcome of interest (i.e., we should know how many
people experienced a heart attack during follow-up and how many did
not). Understanding the distribution of the outcome provides context for
interpreting results and ensures there are enough events to support a
stable logistic regression model. We can check the number who
experienced a heart attack using the <code>table()</code> command as
follows:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" tabindex="-1"></a><span class="co"># check how many people in the sample experienced a heart attack during follow-up</span></span>
<span id="cb16-2"><a href="#cb16-2" tabindex="-1"></a><span class="fu">table</span>(data_reg<span class="sc">$</span>MI_FCHD)</span></code></pre></div>
<pre><code>## 
##    0    1 
## 3577  595</code></pre>
<p>From the output, we can see there are 595 participants who
experienced a heart attack during follow-up and 3577 participants who
did not.</p>
<p>Next, let’s check the distribution of our predictor variables of
interest, using histograms for numerical variabes and tables for
categorical variables, as follows:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" tabindex="-1"></a><span class="co"># check distribution of numerical risk factors</span></span>
<span id="cb18-2"><a href="#cb18-2" tabindex="-1"></a><span class="fu">hist</span>(data_reg<span class="sc">$</span>AGE, <span class="at">breaks =</span> <span class="dv">30</span>)</span></code></pre></div>
<p><img src="Lab_8_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" tabindex="-1"></a><span class="fu">hist</span>(data_reg<span class="sc">$</span>BMI, <span class="at">breaks =</span> <span class="dv">30</span>)</span></code></pre></div>
<p><img src="Lab_8_files/figure-html/unnamed-chunk-15-2.png" width="672" /></p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" tabindex="-1"></a><span class="fu">hist</span>(data_reg<span class="sc">$</span>SYSBP, <span class="at">breaks =</span> <span class="dv">30</span>) </span></code></pre></div>
<p><img src="Lab_8_files/figure-html/unnamed-chunk-15-3.png" width="672" /></p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" tabindex="-1"></a><span class="fu">hist</span>(data_reg<span class="sc">$</span>TOTCHOL, <span class="at">breaks =</span> <span class="dv">30</span>)</span></code></pre></div>
<p><img src="Lab_8_files/figure-html/unnamed-chunk-15-4.png" width="672" /></p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" tabindex="-1"></a><span class="co"># check distribution of categorical risk factors</span></span>
<span id="cb22-2"><a href="#cb22-2" tabindex="-1"></a><span class="fu">table</span>(data_reg<span class="sc">$</span>SEX)</span></code></pre></div>
<pre><code>## 
##    1    2 
## 1808 2364</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" tabindex="-1"></a><span class="fu">table</span>(data_reg<span class="sc">$</span>CURSMOKE)</span></code></pre></div>
<pre><code>## 
##    0    1 
## 2115 2057</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" tabindex="-1"></a><span class="fu">table</span>(data_reg<span class="sc">$</span>DIABETES)</span></code></pre></div>
<pre><code>## 
##    0    1 
## 4066  106</code></pre>
<p>The histograms above show that BMI, systolic blood pressure, and
total cholesterol are right-skewed. While logistic regression does not
require numerical predictor variables to be normally distributed, it
does assume that each continuous predictor has a linear relationship
with the log-odds of the outcome. Skewed predictors may sometimes
violate this assumption. As we move forward with modeling, we’ll need to
keep an eye on whether any transformations (e.g., log or square root) or
other adjustments are needed to better meet the linearity of the logit
assumption. In such cases, achieving more symmetric distributions can
help improve model fit. For now, let’s move on with fitting our initial
logistic regression model.</p>
<p><br></p>
</div>
<div id="fit-logistic-regression-model" class="section level2">
<h2>6. Fit logistic regression model</h2>
<p>In this step, we will use the <code>glm()</code> function to fit a
logistic regression model. Recall that the goal of logistic regression
is to examine how a set of predictor variables (in this case, sex, age,
BMI, blood pressure, cholesterol, smoking status, and diabetes) are
associated with the probability that a participant experienced a heart
attack during the follow-up period.</p>
<p>We will specify <code>family = binomial</code> because our outcome
variable (<code>MI_FCHD</code>) is binary, meaning it takes the value
“1” if a heart attack occurred and “0” if it did not. The binomial
family tells R to use a <em>logit link function</em>, which models the
log-odds of the outcome as a linear combination of the predictors. In
other words, the model estimates how each predictor affects the log-odds
of having a heart attack, holding the other variables constant. This
allows us to understand the relative contribution of each factor to
heart attack risk while adjusting for the others.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" tabindex="-1"></a><span class="co"># fit initial logistic regression model</span></span>
<span id="cb28-2"><a href="#cb28-2" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(MI_FCHD <span class="sc">~</span> SEX <span class="sc">+</span> AGE <span class="sc">+</span> BMI <span class="sc">+</span> SYSBP <span class="sc">+</span> TOTCHOL <span class="sc">+</span> CURSMOKE <span class="sc">+</span> DIABETES, </span>
<span id="cb28-3"><a href="#cb28-3" tabindex="-1"></a>              <span class="at">family =</span> binomial, <span class="at">data =</span> data_reg)</span></code></pre></div>
<p>Just as we did with linear regression, we can use the
<code>summary()</code> function to view the model results, as
follows:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" tabindex="-1"></a><span class="co"># generate a summary of the model</span></span>
<span id="cb29-2"><a href="#cb29-2" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = MI_FCHD ~ SEX + AGE + BMI + SYSBP + TOTCHOL + CURSMOKE + 
##     DIABETES, family = binomial, data = data_reg)
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -7.559888   0.498172 -15.175  &lt; 2e-16 ***
## SEX2        -1.195035   0.101648 -11.757  &lt; 2e-16 ***
## AGE          0.022749   0.006030   3.773 0.000162 ***
## BMI          0.035429   0.011885   2.981 0.002874 ** 
## SYSBP        0.015898   0.002203   7.217 5.33e-13 ***
## TOTCHOL      0.007763   0.001059   7.328 2.33e-13 ***
## CURSMOKE1    0.310982   0.099839   3.115 0.001840 ** 
## DIABETES1    0.905122   0.222462   4.069 4.73e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 3418.4  on 4171  degrees of freedom
## Residual deviance: 3044.3  on 4164  degrees of freedom
## AIC: 3060.3
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>The output provides the results of our logistic regression model -
which, again, estimates how each predictor is associated with the
log-odds of experiencing a heart attack. This may or may not be our
“final” model, but for now, let’s get familiar with the output:</p>
<ul>
<li><strong>Regression coefficients</strong> (labeled “Estimate”)
<ul>
<li>Each Estimate represents the change in the log-odds of having a
heart attack for a one-unit increase in that predictor (holding other
variables constant).</li>
<li>For categorical variables (like SEX2, CURSMOKE1, and DIABETES1), the
coefficient compares the listed category to a reference group (more on
this later).</li>
</ul></li>
<li><strong>Statistical significance</strong>
<ul>
<li>The Pr(&gt;|z|) column indicates whether the coefficient is
statistically significantly different from 0.</li>
<li>Small p-values (e.g., &lt; 0.05) indicate strong evidence that the
predictor is associated with the outcome.</li>
<li>The asterisks (e.g., *<strong>, </strong>) give a quick visual cue
of whether a coefficient is significant.</li>
</ul></li>
<li><strong>Direction of association</strong>
<ul>
<li>A positive coefficient means that an increase in that predictor
increases the log-odds (and therefore the probability) of a heart
attack.</li>
<li>A negative coefficient means that an increase in that predictor
decreases the log-odds (and the probability) of a heart attack.</li>
</ul></li>
<li><strong>Model fit metrics</strong>
<ul>
<li>Null deviance shows how well a model with <em>no predictors</em>
fits the data.</li>
<li>Residual deviance shows the fit of your current model, where a large
reduction from null to residual deviance indicates better model
fit.</li>
<li>AIC (Akaike Information Criterion) is another measure of model
quality, where lower values indicate a better-fitting model when
comparing different models.</li>
</ul></li>
</ul>
<p><br></p>
</div>
<div id="model-diagnostics" class="section level2">
<h2>7. Model diagnostics</h2>
<p>Before we interpret and use our model, we first need to run model
diagnostics to ensure the assumptions of logistic regression are met.
This means checking: (1) whether each numerical predictor variable has a
linear relationship with the log-odds of the outcome, and (2) whether
there is any concerning multicollinearity between predictor
variables.</p>
<p><br></p>
<div id="check-linearity-assumption" class="section level3">
<h3>Check linearity assumption</h3>
<p>We will use the <strong>Box-Tidwell Test</strong> to check whether
each numerical predictor has a linear relationship with the log-odds of
the outcome. This test adds an <em>interaction term</em> between each
numerical variable and its log-transformed version (e.g., AGE *
log(AGE)) to the model. If the relationship between the predictor and
the log-odds is truly linear, this interaction term should
<strong>not</strong> be statistically significant. In a nutshell…</p>
<ul>
<li>If the interaction term is not significant → the linearity
assumption is likely met for that predictor.</li>
<li>If the interaction term is significant → the relationship is likely
nonlinear, and we may need to use a variable transformation to try to
improve linearity.</li>
</ul>
<p>When using the Box-Tidwell Test, we should first make sure that all
values for each numerical predictor variable are greater than 0, as the
log of 0 is undefined. To check whether there are any 0 values, you can
open the <code>data_reg</code> object (click on the object in the
Environment window to open it in a new tab), then click on the column
name for each numerical variable to quickly sort the values from lowest
to highest. If you don’t see any 0 values, you can proceed with the
test. If needed, you can add a small constant (e.g., 0.01) to any
variable that has 0 values.</p>
<p>In our case, there are no 0 values for age, BMI, systolic blood
pressure, or total cholesterol, so we will continue on to the first step
of the test, which is to create new variables for the log of each
numerical predictor, which we can do as follows:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" tabindex="-1"></a><span class="co"># Create new variables for the log of each predictor</span></span>
<span id="cb31-2"><a href="#cb31-2" tabindex="-1"></a>data_reg<span class="sc">$</span>AGE_log <span class="ot">&lt;-</span> <span class="fu">log</span>(data_reg<span class="sc">$</span>AGE)</span>
<span id="cb31-3"><a href="#cb31-3" tabindex="-1"></a>data_reg<span class="sc">$</span>BMI_log <span class="ot">&lt;-</span> <span class="fu">log</span>(data_reg<span class="sc">$</span>BMI)</span>
<span id="cb31-4"><a href="#cb31-4" tabindex="-1"></a>data_reg<span class="sc">$</span>SYSBP_log <span class="ot">&lt;-</span> <span class="fu">log</span>(data_reg<span class="sc">$</span>SYSBP)</span>
<span id="cb31-5"><a href="#cb31-5" tabindex="-1"></a>data_reg<span class="sc">$</span>TOTCHOL_log <span class="ot">&lt;-</span> <span class="fu">log</span>(data_reg<span class="sc">$</span>TOTCHOL)</span></code></pre></div>
<p>Next, we will fit a logistic regression model containing all
predictors of interest. This time, however, we will also include
interaction terms between each numerical predictor variable and its log
version, as follows:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" tabindex="-1"></a><span class="co"># Fit a model including interactions between variables and their log</span></span>
<span id="cb32-2"><a href="#cb32-2" tabindex="-1"></a>bt_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(MI_FCHD <span class="sc">~</span> SEX <span class="sc">+</span> AGE <span class="sc">+</span> <span class="fu">I</span>(AGE<span class="sc">*</span>AGE_log) <span class="sc">+</span></span>
<span id="cb32-3"><a href="#cb32-3" tabindex="-1"></a>                          BMI <span class="sc">+</span> <span class="fu">I</span>(BMI<span class="sc">*</span>BMI_log) <span class="sc">+</span></span>
<span id="cb32-4"><a href="#cb32-4" tabindex="-1"></a>                          SYSBP <span class="sc">+</span> <span class="fu">I</span>(SYSBP<span class="sc">*</span>SYSBP_log) <span class="sc">+</span></span>
<span id="cb32-5"><a href="#cb32-5" tabindex="-1"></a>                          TOTCHOL <span class="sc">+</span> <span class="fu">I</span>(TOTCHOL<span class="sc">*</span>TOTCHOL_log) <span class="sc">+</span></span>
<span id="cb32-6"><a href="#cb32-6" tabindex="-1"></a>                          CURSMOKE <span class="sc">+</span> DIABETES,</span>
<span id="cb32-7"><a href="#cb32-7" tabindex="-1"></a>                <span class="at">data =</span> data_reg, <span class="at">family =</span> binomial)</span>
<span id="cb32-8"><a href="#cb32-8" tabindex="-1"></a><span class="fu">summary</span>(bt_model)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = MI_FCHD ~ SEX + AGE + I(AGE * AGE_log) + BMI + 
##     I(BMI * BMI_log) + SYSBP + I(SYSBP * SYSBP_log) + TOTCHOL + 
##     I(TOTCHOL * TOTCHOL_log) + CURSMOKE + DIABETES, family = binomial, 
##     data = data_reg)
## 
## Coefficients:
##                            Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)              -14.801311   4.663261  -3.174  0.00150 ** 
## SEX2                      -1.172554   0.103948 -11.280  &lt; 2e-16 ***
## AGE                        0.218618   0.336034   0.651  0.51532    
## I(AGE * AGE_log)          -0.039845   0.068102  -0.585  0.55849    
## BMI                        0.329809   0.387075   0.852  0.39418    
## I(BMI * BMI_log)          -0.067996   0.089046  -0.764  0.44510    
## SYSBP                      0.077129   0.098960   0.779  0.43574    
## I(SYSBP * SYSBP_log)      -0.010173   0.016467  -0.618  0.53670    
## TOTCHOL                    0.056288   0.036196   1.555  0.11993    
## I(TOTCHOL * TOTCHOL_log)  -0.007413   0.005493  -1.349  0.17721    
## CURSMOKE1                  0.315481   0.100200   3.149  0.00164 ** 
## DIABETES1                  0.933984   0.222574   4.196 2.71e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 3418.4  on 4171  degrees of freedom
## Residual deviance: 3040.9  on 4160  degrees of freedom
## AIC: 3064.9
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>From the model summary, we can see that none of the interaction terms
are statistically significant, meaning the linearity assumption is
likely met for each numerical predictor, and we won’t need to use any
variable transformations. Yay!</p>
<p><br></p>
</div>
<div id="check-for-multicollinearity" class="section level3">
<h3>Check for multicollinearity</h3>
<p>Next, we will check for multicollinearity between predictor
variables. Recall from our exploration of linear regression that
multicollinearity occurs when two or more predictor variables are highly
correlated. This can cause problems in estimating regression
coefficients. Just as we did in Lab 7, we will use the
<code>check_collinearity()</code> function to generate a Variance
Inflation Factor (VIF) for each variable, as follows:</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" tabindex="-1"></a><span class="co"># check for multicollinearity between numerical predictor variables</span></span>
<span id="cb34-2"><a href="#cb34-2" tabindex="-1"></a><span class="fu">check_collinearity</span>(model1)</span></code></pre></div>
<pre><code>## # Check for Multicollinearity
## 
## Low Correlation
## 
##      Term  VIF   VIF 95% CI adj. VIF Tolerance Tolerance 95% CI
##       SEX 1.12 [1.09, 1.17]     1.06      0.89     [0.86, 0.92]
##       AGE 1.21 [1.17, 1.26]     1.10      0.83     [0.79, 0.85]
##       BMI 1.13 [1.09, 1.17]     1.06      0.89     [0.85, 0.91]
##     SYSBP 1.28 [1.23, 1.33]     1.13      0.78     [0.75, 0.81]
##   TOTCHOL 1.06 [1.03, 1.10]     1.03      0.95     [0.91, 0.97]
##  CURSMOKE 1.14 [1.11, 1.19]     1.07      0.88     [0.84, 0.90]
##  DIABETES 1.02 [1.01, 1.09]     1.01      0.98     [0.92, 0.99]</code></pre>
<p>From the output, we can see the VIF values (second column from the
left) are all close to 1. This means there is no multicollinearity in
our original model. Great!</p>
<p><br></p>
</div>
</div>
<div id="exponentiate-regression-coefficients" class="section level2">
<h2>8. Exponentiate regression coefficients</h2>
<p>Now that we have verified our original model meets assumptions of
logistic regression, we can proceed with interpreting our results.
Recall that the coefficients from a logistic regression model represent
changes in the log-odds of the outcome for a one-unit increase in each
predictor. While this is useful from a modeling standpoint, log-odds can
be hard to interpret intuitively. To make our results more meaningful,
we can <strong>exponentiate</strong> the coefficients using the
<code>exp()</code> function. This converts log-odds to <strong>odds
ratios</strong>, which are easier to interpret in a public health
context. An odds ratio (OR) tells us how the odds of the outcome change
with a one-unit increase in the predictor:</p>
<ul>
<li>OR &gt; 1 → increased odds (the predictor is a risk factor for the
outcome)</li>
<li>OR &lt; 1 → decreased odds (the predictor is a protective factor for
the outcome)</li>
<li>OR = 1 → no association (there is no association between the
predictor and outcome)</li>
</ul>
<p>We can exponentiate the regression coefficients from our model by
nesting the <code>coef()</code> function within the <code>exp()</code>
function and save the result to an R object (called
<code>odds_ratios</code>), as follows:</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" tabindex="-1"></a><span class="co"># exponentiate regression coefficients</span></span>
<span id="cb36-2"><a href="#cb36-2" tabindex="-1"></a>odds_ratios <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">coef</span>(model1))</span></code></pre></div>
<p>Let’s round the odds ratios to three decimal places and put them in a
nice table, as follows:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" tabindex="-1"></a><span class="co"># put odds ratios in a nice table</span></span>
<span id="cb37-2"><a href="#cb37-2" tabindex="-1"></a>odds_ratios <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">round</span>(odds_ratios, <span class="dv">3</span>))</span>
<span id="cb37-3"><a href="#cb37-3" tabindex="-1"></a><span class="fu">print</span>(odds_ratios)</span></code></pre></div>
<pre><code>##             round(odds_ratios, 3)
## (Intercept)                 0.001
## SEX2                        0.303
## AGE                         1.023
## BMI                         1.036
## SYSBP                       1.016
## TOTCHOL                     1.008
## CURSMOKE1                   1.365
## DIABETES1                   2.472</code></pre>
<p>In the output, we see two columns - one listing the predictors of
interest and the other listing the odds ratio associated with each
predictor. In the next section, we’ll discuss how to interpret these
results.</p>
<p><br></p>
</div>
<div id="interpret-odds-ratios" class="section level2">
<h2>9. Interpret odds ratios</h2>
<p>If you take away only one thing from this Lab, let it be this: how to
correctly interpret an odds ratio. Odds ratios are one of the most
commonly reported effect measures in public health research involving
binary outcomes. They tell us how the odds of an outcome (like having a
heart attack) change in relation to a predictor variable:</p>
<ul>
<li>For a continuous variable (like age, BMI, systolic blood pressure,
or total cholesterol), the odds ratio represents the change in the odds
of the outcome associated with a one-unit increase in that variable,
holding all other variables constant.
<ul>
<li>To calculate the percent change in odds, we will use the following
formula: (OR−1) × 100 = % change in odds</li>
</ul></li>
<li>For a categorical variable (like sex, smoking status, or diabetes
status), the odds ratio compares the odds of the outcome for one
category <em>relative to a reference category</em>.</li>
</ul>
<p>For example, we can interpret the odds ratios we obtained in the
previous section as follows:</p>
<ul>
<li><strong>SEX2 = 0.303</strong> → Participants coded as SEX=2
(females) have 69.7% lower odds of experiencing a heart attack during
follow-up compared to males (the reference group, SEX=1), holding all
other variables constant.</li>
<li><strong>AGE = 1.023</strong> → For each additional year of age, the
odds of experiencing a heart attack increase by 2.3%, holding all other
variables constant.</li>
<li><strong>BMI = 1.036</strong> → For each one-unit increase in BMI,
the odds of having a heart attack increase by 3.6%, holding all other
variables constant.</li>
<li><strong>SYSBP = 1.016</strong> → For each 1 mmHg increase in
systolic blood pressure, the odds of a heart attack increase by 1.6%,
holding all other variables constant.</li>
<li><strong>TOTCHOL = 1.008</strong> → For each one-unit (mg/dL)
increase in total cholesterol, the odds of having a heart attack
increase by 0.8%, holding all other variables constant.</li>
<li><strong>CURSMOKE1 = 1.365</strong> → Current smokers (CURSMOKE=1)
have 36.5% higher odds of experiencing a heart attack compared to
non-smokers, holding all other variables constant.</li>
<li><strong>DIABETES1 = 2.472</strong> → Participants with diabetes have
2.472 times the odds of having a heart attack compared to those without
diabetes — meaning their odds are 147.2% higher, holding all other
variables constant.</li>
</ul>
<p><br></p>
</div>
</div>
<div id="summary" class="section level1">
<h1>Summary</h1>
<p>In Lab 8, you learned how to fit a logistic regression model to
explore the relationship between multiple predictors and a binary health
outcome. You also checked model assumptions and converted regression
coefficients into odds ratios to make results easier to interpret. Most
importantly, you practiced interpreting odds ratios, which is a core
skill in public health research.</p>
<p>Logistic regression is a powerful tool for identifying and
quantifying risk factors for disease. By understanding how variables
like age, smoking, or diabetes affect the odds of a health outcome,
public health professionals can make informed decisions about prevention
strategies, resource allocation, and health policy.</p>
<p>When you are ready, please submit the following to the Lab 8
assignment page on Canvas:</p>
<ol style="list-style-type: decimal">
<li>An R Markdown document, which has a <code>.Rmd</code> extension</li>
<li>A knitted <code>.html</code> file</li>
</ol>
<p>Please reach out to me at <a href="mailto:jenny.wagner@csus.edu"
class="email">jenny.wagner@csus.edu</a> if you have any questions. See
you in class!</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
